In [2]:
import pandas as pd

notas = {
    'aluno': ['Pedro', 'Lucas', 'Luan', 'Felipe', 'Ricardo'],
    'nota_prova1':[6.8, 9.4, 8.2, 5.3, 7.8],
    'nota_prova2':[5.8, 8.2, 9.1, 7.2, 9.5],
    'nota_prova3':[8.4, 9.1, 7.4, 8.3, 9.8]
}
df = pd.DataFrame(notas)
df

     aluno  nota_prova1  nota_prova2  nota_prova3
0    Pedro          6.8          5.8          8.4
1    Lucas          9.4          8.2          9.1
2     Luan          8.2          9.1          7.4
3   Felipe          5.3          7.2          8.3
4  Ricardo          7.8          9.5          9.8

In [3]:
df_melt = pd.melt(
    df,
    id_vars=['aluno'],
    value_vars=['nota_prova1', 'nota_prova2', 'nota_prova3'],
    var_name='prova',
    value_name='notas'
)

In [4]:
df_melt

      aluno        prova  notas
0     Pedro  nota_prova1    6.8
1     Lucas  nota_prova1    9.4
2      Luan  nota_prova1    8.2
3    Felipe  nota_prova1    5.3
4   Ricardo  nota_prova1    7.8
5     Pedro  nota_prova2    5.8
6     Lucas  nota_prova2    8.2
7      Luan  nota_prova2    9.1
8    Felipe  nota_prova2    7.2
9   Ricardo  nota_prova2    9.5
10    Pedro  nota_prova3    8.4
11    Lucas  nota_prova3    9.1
12     Luan  nota_prova3    7.4
13   Felipe  nota_prova3    8.3
14  Ricardo  nota_prova3    9.8