In [1]:
import pandas as pd

report = {
    'departamento':['Tecnologia', 'Recursos Humanos', 'Marketing',
                    'Financeiro', 'Operacoes', 'Administrativo'
                    ],
    'categoria_despesa':['Software e equipamentos', 'Salarios e benficios', 'Publicidade e campanhas', 'Taxas bancarias e servicos financeiros', 'Materiais e manutencao', 'Aluguel e despesas de escritorio'],
    'despesa_01-2024':[15000, 25000, 12000, 8000, 30000, 18000],
    'despesa_02-2024':[18500, 25500, 20000, 7500, 32500, 17800],
    'despesa_03-2024':[16200, 26000, 17500, 8300, 31000, 19200]

}
df = pd.DataFrame(report)
df

,departamento,categoria_despesa,despesa_01-2024,despesa_02-2024,despesa_03-2024
0,Tecnologia,Software e equipamentos,15000,18500,16200
1,Recursos Humanos,Salarios e benficios,25000,25500,26000
2,Marketing,Publicidade e campanhas,12000,20000,17500
3,Financeiro,Taxas bancarias e servicos financeiros,8000,7500,8300
4,Operacoes,Materiais e manutencao,30000,32500,31000
5,Administrativo,Aluguel e despesas de escritorio,18000,17800,19200

In [2]:
df_melt = df.melt(
    id_vars=['departamento', 'categoria_despesa'],
    value_vars=['despesa_01-2024', 'despesa_02-2024', 'despesa_03-2024'],
    var_name='mes_despesa',
    value_name='valor_despesa'
)
df_melt

,departamento,categoria_despesa,mes_despesa,valor_despesa
0,Tecnologia,Software e equipamentos,despesa_01-2024,15000
1,Recursos Humanos,Salarios e benficios,despesa_01-2024,25000
2,Marketing,Publicidade e campanhas,despesa_01-2024,12000
3,Financeiro,Taxas bancarias e servicos financeiros,despesa_01-2024,8000
4,Operacoes,Materiais e manutencao,despesa_01-2024,30000
5,Administrativo,Aluguel e despesas de escritorio,despesa_01-2024,18000
6,Tecnologia,Software e equipamentos,despesa_02-2024,18500
7,Recursos Humanos,Salarios e benficios,despesa_02-2024,25500
8,Marketing,Publicidade e campanhas,despesa_02-2024,20000
9,Financeiro,Taxas bancarias e servicos financeiros,despesa_02-2024,7500
10,Operacoes,Materiais e manutencao,despesa_02-2024,32500
11,Administrativo,Aluguel e despesas de escritorio,despesa_02-2024,17800
12,Tecnologia,Software e equipamentos,despesa_03-2024,16200
13,Recursos Humanos,Salarios e benficios,despesa_03-2024,26000
14,Marketing,Publicidade e campanhas,despesa_03-2024,17500
15,Financeiro,Taxas bancarias e servicos financeiros,despesa_03-2024,8300
16,Operacoes,Materiais e manutencao,despesa_03-2024,31000
17,Administrativo,Aluguel e despesas de escritorio,despesa_03-2024,19200

In [3]:
df_melt.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   departamento       18 non-null     str
 1   categoria_despesa  18 non-null     str
 2   mes_despesa        18 non-null     str
 3   valor_despesa      18 non-null     int64
dtypes: int64(1), str(3)
memory usage: 708.0 bytes

In [4]:
df_melt[['despesa', 'mes']] = df_melt['mes_despesa'].str.rsplit('_', n=1, expand=True)

In [5]:
df_melt

,departamento,categoria_despesa,mes_despesa,valor_despesa,despesa,mes
0,Tecnologia,Software e equipamentos,despesa_01-2024,15000,despesa,01-2024
1,Recursos Humanos,Salarios e benficios,despesa_01-2024,25000,despesa,01-2024
2,Marketing,Publicidade e campanhas,despesa_01-2024,12000,despesa,01-2024
3,Financeiro,Taxas bancarias e servicos financeiros,despesa_01-2024,8000,despesa,01-2024
4,Operacoes,Materiais e manutencao,despesa_01-2024,30000,despesa,01-2024
5,Administrativo,Aluguel e despesas de escritorio,despesa_01-2024,18000,despesa,01-2024
6,Tecnologia,Software e equipamentos,despesa_02-2024,18500,despesa,02-2024
7,Recursos Humanos,Salarios e benficios,despesa_02-2024,25500,despesa,02-2024
8,Marketing,Publicidade e campanhas,despesa_02-2024,20000,despesa,02-2024
9,Financeiro,Taxas bancarias e servicos financeiros,despesa_02-2024,7500,despesa,02-2024
10,Operacoes,Materiais e manutencao,despesa_02-2024,32500,despesa,02-2024
11,Administrativo,Aluguel e despesas de escritorio,despesa_02-2024,17800,despesa,02-2024
12,Tecnologia,Software e equipamentos,despesa_03-2024,16200,despesa,03-2024
13,Recursos Humanos,Salarios e benficios,despesa_03-2024,26000,despesa,03-2024
14,Marketing,Publicidade e campanhas,despesa_03-2024,17500,despesa,03-2024
15,Financeiro,Taxas bancarias e servicos financeiros,despesa_03-2024,8300,despesa,03-2024
16,Operacoes,Materiais e manutencao,despesa_03-2024,31000,despesa,03-2024
17,Administrativo,Aluguel e despesas de escritorio,despesa_03-2024,19200,despesa,03-2024

In [6]:
df_melt = df_melt.drop(columns=['mes_despesa', 'despesa'])

In [7]:
df_melt

,departamento,categoria_despesa,valor_despesa,mes
0,Tecnologia,Software e equipamentos,15000,01-2024
1,Recursos Humanos,Salarios e benficios,25000,01-2024
2,Marketing,Publicidade e campanhas,12000,01-2024
3,Financeiro,Taxas bancarias e servicos financeiros,8000,01-2024
4,Operacoes,Materiais e manutencao,30000,01-2024
5,Administrativo,Aluguel e despesas de escritorio,18000,01-2024
6,Tecnologia,Software e equipamentos,18500,02-2024
7,Recursos Humanos,Salarios e benficios,25500,02-2024
8,Marketing,Publicidade e campanhas,20000,02-2024
9,Financeiro,Taxas bancarias e servicos financeiros,7500,02-2024
10,Operacoes,Materiais e manutencao,32500,02-2024
11,Administrativo,Aluguel e despesas de escritorio,17800,02-2024
12,Tecnologia,Software e equipamentos,16200,03-2024
13,Recursos Humanos,Salarios e benficios,26000,03-2024
14,Marketing,Publicidade e campanhas,17500,03-2024
15,Financeiro,Taxas bancarias e servicos financeiros,8300,03-2024
16,Operacoes,Materiais e manutencao,31000,03-2024
17,Administrativo,Aluguel e despesas de escritorio,19200,03-2024

In [8]:
df_melt['mes'] = pd.to_datetime(df_melt['mes'], format='%m-%Y')
df_melt

,departamento,categoria_despesa,valor_despesa,mes
0,Tecnologia,Software e equipamentos,15000,2024-01-01
1,Recursos Humanos,Salarios e benficios,25000,2024-01-01
2,Marketing,Publicidade e campanhas,12000,2024-01-01
3,Financeiro,Taxas bancarias e servicos financeiros,8000,2024-01-01
4,Operacoes,Materiais e manutencao,30000,2024-01-01
5,Administrativo,Aluguel e despesas de escritorio,18000,2024-01-01
6,Tecnologia,Software e equipamentos,18500,2024-02-01
7,Recursos Humanos,Salarios e benficios,25500,2024-02-01
8,Marketing,Publicidade e campanhas,20000,2024-02-01
9,Financeiro,Taxas bancarias e servicos financeiros,7500,2024-02-01
10,Operacoes,Materiais e manutencao,32500,2024-02-01
11,Administrativo,Aluguel e despesas de escritorio,17800,2024-02-01
12,Tecnologia,Software e equipamentos,16200,2024-03-01
13,Recursos Humanos,Salarios e benficios,26000,2024-03-01
14,Marketing,Publicidade e campanhas,17500,2024-03-01
15,Financeiro,Taxas bancarias e servicos financeiros,8300,2024-03-01
16,Operacoes,Materiais e manutencao,31000,2024-03-01
17,Administrativo,Aluguel e despesas de escritorio,19200,2024-03-01

In [9]:
df_melt.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   departamento       18 non-null     str
 1   categoria_despesa  18 non-null     str
 2   valor_despesa      18 non-null     int64
 3   mes                18 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(1), str(2)
memory usage: 708.0 bytes

In [10]:
df_melt['mes'] = df_melt['mes'].dt.month_name(locale='pt_BR.UTF-8')
df_melt

,departamento,categoria_despesa,valor_despesa,mes
0,Tecnologia,Software e equipamentos,15000,Janeiro
1,Recursos Humanos,Salarios e benficios,25000,Janeiro
2,Marketing,Publicidade e campanhas,12000,Janeiro
3,Financeiro,Taxas bancarias e servicos financeiros,8000,Janeiro
4,Operacoes,Materiais e manutencao,30000,Janeiro
5,Administrativo,Aluguel e despesas de escritorio,18000,Janeiro
6,Tecnologia,Software e equipamentos,18500,Fevereiro
7,Recursos Humanos,Salarios e benficios,25500,Fevereiro
8,Marketing,Publicidade e campanhas,20000,Fevereiro
9,Financeiro,Taxas bancarias e servicos financeiros,7500,Fevereiro
10,Operacoes,Materiais e manutencao,32500,Fevereiro
11,Administrativo,Aluguel e despesas de escritorio,17800,Fevereiro
12,Tecnologia,Software e equipamentos,16200,Março
13,Recursos Humanos,Salarios e benficios,26000,Março
14,Marketing,Publicidade e campanhas,17500,Março
15,Financeiro,Taxas bancarias e servicos financeiros,8300,Março
16,Operacoes,Materiais e manutencao,31000,Março
17,Administrativo,Aluguel e despesas de escritorio,19200,Março

In [11]:
df_pivot_table = df_melt.pivot_table(
    index=['categoria_despesa'],
    columns=['mes'],
    values='valor_despesa',
    aggfunc='sum'
)

df_pivot_table

mes                                     Fevereiro  Janeiro  Março
categoria_despesa
Aluguel e despesas de escritorio            17800    18000  19200
Materiais e manutencao                      32500    30000  31000
Publicidade e campanhas                     20000    12000  17500
Salarios e benficios                        25500    25000  26000
Software e equipamentos                     18500    15000  16200
Taxas bancarias e servicos financeiros       7500     8000   8300