In [2]:
import pandas as pd

dados = {
    'produto_id':[1,2,3,4,5,6],
    'loja':['Amazon', 'Amazon','Apple', 'Apple', 'Samsung', 'Samsung'],
    'produtos':['ALexa', 'Kindle', 'Iphone 17 Pro Max', 'Iphone 17 Pro', 'Samsung S24 Ultra', 'Samsung ZFLIP 7' ],
    'data_cadastro':[
        '01-02-2024', '01-30-2024',
        '02-10-2024', '01-22-2024',
        '03-12-2024', '03-22-2024'
    ],
    'venda_01-2024':[10912, 5832, 3482, 2365, 5978, 1784],
    'venda_02-2024':[9132, 2813, 2237, 3469, 3948, 884],
    'venda_03-2024':[8131, 3432, 1482, 2065, 4378, 314]
}

df = pd.DataFrame(dados)
df

,produto_id,loja,produtos,data_cadastro,venda_01-2024,venda_02-2024,venda_03-2024
0,1,Amazon,ALexa,01-02-2024,10912,9132,8131
1,2,Amazon,Kindle,01-30-2024,5832,2813,3432
2,3,Apple,Iphone 17 Pro Max,02-10-2024,3482,2237,1482
3,4,Apple,Iphone 17 Pro,01-22-2024,2365,3469,2065
4,5,Samsung,Samsung S24 Ultra,03-12-2024,5978,3948,4378
5,6,Samsung,Samsung ZFLIP 7,03-22-2024,1784,884,314

In [3]:
df_melt = pd.melt(
    df,
    id_vars=['produto_id', 'loja', 'data_cadastro', 'produtos'],
    value_vars=['venda_01-2024', 'venda_02-2024', 'venda_03-2024'],
    var_name='relatorio_mes',
    value_name='total_vendas'
)
df_melt

,produto_id,loja,data_cadastro,produtos,relatorio_mes,total_vendas
0,1,Amazon,01-02-2024,ALexa,venda_01-2024,10912
1,2,Amazon,01-30-2024,Kindle,venda_01-2024,5832
2,3,Apple,02-10-2024,Iphone 17 Pro Max,venda_01-2024,3482
3,4,Apple,01-22-2024,Iphone 17 Pro,venda_01-2024,2365
4,5,Samsung,03-12-2024,Samsung S24 Ultra,venda_01-2024,5978
5,6,Samsung,03-22-2024,Samsung ZFLIP 7,venda_01-2024,1784
6,1,Amazon,01-02-2024,ALexa,venda_02-2024,9132
7,2,Amazon,01-30-2024,Kindle,venda_02-2024,2813
8,3,Apple,02-10-2024,Iphone 17 Pro Max,venda_02-2024,2237
9,4,Apple,01-22-2024,Iphone 17 Pro,venda_02-2024,3469
10,5,Samsung,03-12-2024,Samsung S24 Ultra,venda_02-2024,3948
11,6,Samsung,03-22-2024,Samsung ZFLIP 7,venda_02-2024,884
12,1,Amazon,01-02-2024,ALexa,venda_03-2024,8131
13,2,Amazon,01-30-2024,Kindle,venda_03-2024,3432
14,3,Apple,02-10-2024,Iphone 17 Pro Max,venda_03-2024,1482
15,4,Apple,01-22-2024,Iphone 17 Pro,venda_03-2024,2065
16,5,Samsung,03-12-2024,Samsung S24 Ultra,venda_03-2024,4378
17,6,Samsung,03-22-2024,Samsung ZFLIP 7,venda_03-2024,314

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   produto_id     6 non-null      int64
 1   loja           6 non-null      str
 2   produtos       6 non-null      str
 3   data_cadastro  6 non-null      str
 4   venda_01-2024  6 non-null      int64
 5   venda_02-2024  6 non-null      int64
 6   venda_03-2024  6 non-null      int64
dtypes: int64(4), str(3)
memory usage: 468.0 bytes

In [4]:
df_melt['data_cadastro'] = pd.to_datetime(df_melt['data_cadastro'])

In [5]:
df_melt[['relatorio','data_venda']] = df_melt['relatorio_mes'].str.rsplit('_', n=1, expand=True)

In [6]:
df_melt

,produto_id,loja,data_cadastro,produtos,relatorio_mes,total_vendas,relatorio,data_venda
0,1,Amazon,2024-01-02,ALexa,venda_01-2024,10912,venda,01-2024
1,2,Amazon,2024-01-30,Kindle,venda_01-2024,5832,venda,01-2024
2,3,Apple,2024-02-10,Iphone 17 Pro Max,venda_01-2024,3482,venda,01-2024
3,4,Apple,2024-01-22,Iphone 17 Pro,venda_01-2024,2365,venda,01-2024
4,5,Samsung,2024-03-12,Samsung S24 Ultra,venda_01-2024,5978,venda,01-2024
5,6,Samsung,2024-03-22,Samsung ZFLIP 7,venda_01-2024,1784,venda,01-2024
6,1,Amazon,2024-01-02,ALexa,venda_02-2024,9132,venda,02-2024
7,2,Amazon,2024-01-30,Kindle,venda_02-2024,2813,venda,02-2024
8,3,Apple,2024-02-10,Iphone 17 Pro Max,venda_02-2024,2237,venda,02-2024
9,4,Apple,2024-01-22,Iphone 17 Pro,venda_02-2024,3469,venda,02-2024
10,5,Samsung,2024-03-12,Samsung S24 Ultra,venda_02-2024,3948,venda,02-2024
11,6,Samsung,2024-03-22,Samsung ZFLIP 7,venda_02-2024,884,venda,02-2024
12,1,Amazon,2024-01-02,ALexa,venda_03-2024,8131,venda,03-2024
13,2,Amazon,2024-01-30,Kindle,venda_03-2024,3432,venda,03-2024
14,3,Apple,2024-02-10,Iphone 17 Pro Max,venda_03-2024,1482,venda,03-2024
15,4,Apple,2024-01-22,Iphone 17 Pro,venda_03-2024,2065,venda,03-2024
16,5,Samsung,2024-03-12,Samsung S24 Ultra,venda_03-2024,4378,venda,03-2024
17,6,Samsung,2024-03-22,Samsung ZFLIP 7,venda_03-2024,314,venda,03-2024

In [7]:
df_melt = df_melt.drop(columns=['relatorio_mes', 'relatorio'])

In [8]:
df_melt

,produto_id,loja,data_cadastro,produtos,total_vendas,data_venda
0,1,Amazon,2024-01-02,ALexa,10912,01-2024
1,2,Amazon,2024-01-30,Kindle,5832,01-2024
2,3,Apple,2024-02-10,Iphone 17 Pro Max,3482,01-2024
3,4,Apple,2024-01-22,Iphone 17 Pro,2365,01-2024
4,5,Samsung,2024-03-12,Samsung S24 Ultra,5978,01-2024
5,6,Samsung,2024-03-22,Samsung ZFLIP 7,1784,01-2024
6,1,Amazon,2024-01-02,ALexa,9132,02-2024
7,2,Amazon,2024-01-30,Kindle,2813,02-2024
8,3,Apple,2024-02-10,Iphone 17 Pro Max,2237,02-2024
9,4,Apple,2024-01-22,Iphone 17 Pro,3469,02-2024
10,5,Samsung,2024-03-12,Samsung S24 Ultra,3948,02-2024
11,6,Samsung,2024-03-22,Samsung ZFLIP 7,884,02-2024
12,1,Amazon,2024-01-02,ALexa,8131,03-2024
13,2,Amazon,2024-01-30,Kindle,3432,03-2024
14,3,Apple,2024-02-10,Iphone 17 Pro Max,1482,03-2024
15,4,Apple,2024-01-22,Iphone 17 Pro,2065,03-2024
16,5,Samsung,2024-03-12,Samsung S24 Ultra,4378,03-2024
17,6,Samsung,2024-03-22,Samsung ZFLIP 7,314,03-2024

In [9]:
df_melt.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   produto_id     18 non-null     int64
 1   loja           18 non-null     str
 2   data_cadastro  18 non-null     datetime64[us]
 3   produtos       18 non-null     str
 4   total_vendas   18 non-null     int64
 5   data_venda     18 non-null     str
dtypes: datetime64[us](1), int64(2), str(3)
memory usage: 996.0 bytes

In [11]:
df_melt['data_venda'] = pd.to_datetime(df_melt['data_venda'], format='%m/%Y')

In [12]:
df_melt

,produto_id,loja,data_cadastro,produtos,total_vendas,data_venda
0,1,Amazon,2024-01-02,ALexa,10912,2024-01-01
1,2,Amazon,2024-01-30,Kindle,5832,2024-01-01
2,3,Apple,2024-02-10,Iphone 17 Pro Max,3482,2024-01-01
3,4,Apple,2024-01-22,Iphone 17 Pro,2365,2024-01-01
4,5,Samsung,2024-03-12,Samsung S24 Ultra,5978,2024-01-01
5,6,Samsung,2024-03-22,Samsung ZFLIP 7,1784,2024-01-01
6,1,Amazon,2024-01-02,ALexa,9132,2024-02-01
7,2,Amazon,2024-01-30,Kindle,2813,2024-02-01
8,3,Apple,2024-02-10,Iphone 17 Pro Max,2237,2024-02-01
9,4,Apple,2024-01-22,Iphone 17 Pro,3469,2024-02-01
10,5,Samsung,2024-03-12,Samsung S24 Ultra,3948,2024-02-01
11,6,Samsung,2024-03-22,Samsung ZFLIP 7,884,2024-02-01
12,1,Amazon,2024-01-02,ALexa,8131,2024-03-01
13,2,Amazon,2024-01-30,Kindle,3432,2024-03-01
14,3,Apple,2024-02-10,Iphone 17 Pro Max,1482,2024-03-01
15,4,Apple,2024-01-22,Iphone 17 Pro,2065,2024-03-01
16,5,Samsung,2024-03-12,Samsung S24 Ultra,4378,2024-03-01
17,6,Samsung,2024-03-22,Samsung ZFLIP 7,314,2024-03-01

In [13]:
def classificar_produto(mes_cadastro, mes_venda):
    d1 = mes_cadastro.to_period('M')
    d2 = mes_venda.to_period('M')
    sub = d2 - d1
    if (sub.n >= 0) and (sub.n <= 3):
        return 'Novo'
    else:
        return 'veterano'

In [14]:
df_melt['status_produto'] = df_melt.apply(lambda x: classificar_produto(x['data_cadastro'], x['data_venda']), axis=1)

In [15]:
df_melt

,produto_id,loja,data_cadastro,produtos,total_vendas,data_venda,status_produto
0,1,Amazon,2024-01-02,ALexa,10912,2024-01-01,Novo
1,2,Amazon,2024-01-30,Kindle,5832,2024-01-01,Novo
2,3,Apple,2024-02-10,Iphone 17 Pro Max,3482,2024-01-01,veterano
3,4,Apple,2024-01-22,Iphone 17 Pro,2365,2024-01-01,Novo
4,5,Samsung,2024-03-12,Samsung S24 Ultra,5978,2024-01-01,veterano
5,6,Samsung,2024-03-22,Samsung ZFLIP 7,1784,2024-01-01,veterano
6,1,Amazon,2024-01-02,ALexa,9132,2024-02-01,Novo
7,2,Amazon,2024-01-30,Kindle,2813,2024-02-01,Novo
8,3,Apple,2024-02-10,Iphone 17 Pro Max,2237,2024-02-01,Novo
9,4,Apple,2024-01-22,Iphone 17 Pro,3469,2024-02-01,Novo
10,5,Samsung,2024-03-12,Samsung S24 Ultra,3948,2024-02-01,veterano
11,6,Samsung,2024-03-22,Samsung ZFLIP 7,884,2024-02-01,veterano
12,1,Amazon,2024-01-02,ALexa,8131,2024-03-01,Novo
13,2,Amazon,2024-01-30,Kindle,3432,2024-03-01,Novo
14,3,Apple,2024-02-10,Iphone 17 Pro Max,1482,2024-03-01,Novo
15,4,Apple,2024-01-22,Iphone 17 Pro,2065,2024-03-01,Novo
16,5,Samsung,2024-03-12,Samsung S24 Ultra,4378,2024-03-01,Novo
17,6,Samsung,2024-03-22,Samsung ZFLIP 7,314,2024-03-01,Novo

In [17]:
df_melt.groupby(['loja','data_venda'])['total_vendas'].sum()

loja     data_venda
Amazon   2024-01-01    16744
         2024-02-01    11945
         2024-03-01    11563
Apple    2024-01-01     5847
         2024-02-01     5706
         2024-03-01     3547
Samsung  2024-01-01     7762
         2024-02-01     4832
         2024-03-01     4692
Name: total_vendas, dtype: int64

In [19]:
valor_minimo =  2500
filter = df_melt[df_melt['total_vendas'] < valor_minimo]

In [20]:
filter

,produto_id,loja,data_cadastro,produtos,total_vendas,data_venda,status_produto
3,4,Apple,2024-01-22,Iphone 17 Pro,2365,2024-01-01,Novo
5,6,Samsung,2024-03-22,Samsung ZFLIP 7,1784,2024-01-01,veterano
8,3,Apple,2024-02-10,Iphone 17 Pro Max,2237,2024-02-01,Novo
11,6,Samsung,2024-03-22,Samsung ZFLIP 7,884,2024-02-01,veterano
14,3,Apple,2024-02-10,Iphone 17 Pro Max,1482,2024-03-01,Novo
15,4,Apple,2024-01-22,Iphone 17 Pro,2065,2024-03-01,Novo
17,6,Samsung,2024-03-22,Samsung ZFLIP 7,314,2024-03-01,Novo