In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(r"C:\Users\ruans\OneDrive\Documentos\Material curso engenharia de dados\Python+-+SGBDS\Arquivos\05.+SQL+Server\05. SQL Server\Origem\Origem\arquivos_csv\Clientes.csv", delimiter=',')
df

In [ ]:
df['full_name'] = df['first_name'] + ' ' + df['last_name']
df

In [ ]:
df

Convertendo a coluna 'created_at' para o formato de data

In [ ]:
df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')

In [ ]:
print(df['created_at'].dtypes)

Adicionando coluna com o ano

In [ ]:
df['ano'] = df['created_at'].dt.year

Adicionando coluna com o mês

In [17]:
df['mes'] = df['created_at'].dt.month

Adicionando coluna com o dia

In [18]:
df['dia'] = df['created_at'].dt.day

In [19]:
df

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals,full_name,ano,mes,dia
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16,Marta Jesus,2017,11,1
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17,Luana Almeida,2017,10,16
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN,Frida Mendes,2018,6,16
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN,Daniela Avelino,2018,1,17
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12,Romário Teixeira,2018,8,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,2018-10-01 11:35:59,Mariana,Rosa,mariana@usuario.com,9 3139-2145,Brasil,NaN,NaN,NaN,NaN,Mariana Rosa,2018,10,1
96,96,2018-01-23 19:14:21,Paulo,Câmara,paulo@usuario.com,9 4785-1135,Brasil,Sergipe,Praça 73 do Estado Sergipe,219.0,Apto 6,Paulo Câmara,2018,1,23
97,97,2018-07-04 18:45:41,Marta,Góes,marta@teste.com,9 4102-4352,Brasil,Paraná,Rua 61 do Estado Paraná,402.0,Apto 24,Marta Góes,2018,7,4
98,98,2018-01-24 16:21:06,Cibele,Costa,cibele@meu_email.com,9 4211-6968,Brasil,Mato Grosso,Praça 75 do Estado Mato Grosso,24.0,NaN,Cibele Costa,2018,1,24
99,99,2018-07-24 08:26:27,Jéssica,Jesus,jéssica@usuario.com,9 6100-1466,Brasil,Paraná,Avenida 19 do Estado Paraná,738.0,Conjunto 22,Jéssica Jesus,2018,7,24

Adicionando coluna com horas, minutos e segundos

In [20]:
df['horas'] = df['created_at'].dt.hour
df['minutos'] = df['created_at'].dt.minute
df['segundos'] = df['created_at'].dt.second
df

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals,full_name,ano,mes,dia,horas,minutos,segundos
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16,Marta Jesus,2017,11,1,14,45,41
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17,Luana Almeida,2017,10,16,0,50,39
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN,Frida Mendes,2018,6,16,17,51,29
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN,Daniela Avelino,2018,1,17,3,2,58
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12,Romário Teixeira,2018,8,6,7,24,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,2018-10-01 11:35:59,Mariana,Rosa,mariana@usuario.com,9 3139-2145,Brasil,NaN,NaN,NaN,NaN,Mariana Rosa,2018,10,1,11,35,59
96,96,2018-01-23 19:14:21,Paulo,Câmara,paulo@usuario.com,9 4785-1135,Brasil,Sergipe,Praça 73 do Estado Sergipe,219.0,Apto 6,Paulo Câmara,2018,1,23,19,14,21
97,97,2018-07-04 18:45:41,Marta,Góes,marta@teste.com,9 4102-4352,Brasil,Paraná,Rua 61 do Estado Paraná,402.0,Apto 24,Marta Góes,2018,7,4,18,45,41
98,98,2018-01-24 16:21:06,Cibele,Costa,cibele@meu_email.com,9 4211-6968,Brasil,Mato Grosso,Praça 75 do Estado Mato Grosso,24.0,NaN,Cibele Costa,2018,1,24,16,21,6
99,99,2018-07-24 08:26:27,Jéssica,Jesus,jéssica@usuario.com,9 6100-1466,Brasil,Paraná,Avenida 19 do Estado Paraná,738.0,Conjunto 22,Jéssica Jesus,2018,7,24,8,26,27

juntando script

In [21]:
import pandas as pd
df = pd.read_csv(r"C:\Users\ruans\OneDrive\Documentos\Material curso engenharia de dados\Python+-+SGBDS\Arquivos\05.+SQL+Server\05. SQL Server\Origem\Origem\arquivos_csv\Clientes.csv", delimiter=',')

df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')
df['ano'] = df['created_at'].dt.year
df['mes'] = df['created_at'].dt.month
df['dia'] = df['created_at'].dt.day

df['horas'] = df['created_at'].dt.hour
df['minutos'] = df['created_at'].dt.minute
df['segundos'] = df['created_at'].dt.second

df

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals,ano,mes,dia,horas,minutos,segundos
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16,2017,11,1,14,45,41
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17,2017,10,16,0,50,39
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN,2018,6,16,17,51,29
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN,2018,1,17,3,2,58
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12,2018,8,6,7,24,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,2018-10-01 11:35:59,Mariana,Rosa,mariana@usuario.com,9 3139-2145,Brasil,NaN,NaN,NaN,NaN,2018,10,1,11,35,59
96,96,2018-01-23 19:14:21,Paulo,Câmara,paulo@usuario.com,9 4785-1135,Brasil,Sergipe,Praça 73 do Estado Sergipe,219.0,Apto 6,2018,1,23,19,14,21
97,97,2018-07-04 18:45:41,Marta,Góes,marta@teste.com,9 4102-4352,Brasil,Paraná,Rua 61 do Estado Paraná,402.0,Apto 24,2018,7,4,18,45,41
98,98,2018-01-24 16:21:06,Cibele,Costa,cibele@meu_email.com,9 4211-6968,Brasil,Mato Grosso,Praça 75 do Estado Mato Grosso,24.0,NaN,2018,1,24,16,21,6
99,99,2018-07-24 08:26:27,Jéssica,Jesus,jéssica@usuario.com,9 6100-1466,Brasil,Paraná,Avenida 19 do Estado Paraná,738.0,Conjunto 22,2018,7,24,8,26,27