In [2]:
import pandas as pd

report= {
    'produto': ['Samsung ZFold 8', 'Galaxy A57', 'Samsung S26 Ultra', 'Samsung ZFlip8', 'Galaxy A17'],
    'estoque_01':[8, 20, 5, 8, 25 ],
    'estoque_02':[5, 3, 2, 4, 10],
    'estoque_03':[6, 17, 3, 8, 15]
}

df = pd.DataFrame(report)
df

             produto  estoque_01  estoque_02  estoque_03
0    Samsung ZFold 8           8           5           6
1         Galaxy A57          20           3          17
2  Samsung S26 Ultra           5           2           3
3     Samsung ZFlip8           8           4           8
4         Galaxy A17          25          10          15

In [3]:
df_melt = df.melt(
    id_vars=['produto'],
    value_vars=['estoque_01','estoque_02','estoque_03'],
    var_name='mes',
    value_name='quantidade_estoque'
)

df_melt

              produto         mes  quantidade_estoque
0     Samsung ZFold 8  estoque_01                   8
1          Galaxy A57  estoque_01                  20
2   Samsung S26 Ultra  estoque_01                   5
3      Samsung ZFlip8  estoque_01                   8
4          Galaxy A17  estoque_01                  25
5     Samsung ZFold 8  estoque_02                   5
6          Galaxy A57  estoque_02                   3
7   Samsung S26 Ultra  estoque_02                   2
8      Samsung ZFlip8  estoque_02                   4
9          Galaxy A17  estoque_02                  10
10    Samsung ZFold 8  estoque_03                   6
11         Galaxy A57  estoque_03                  17
12  Samsung S26 Ultra  estoque_03                   3
13     Samsung ZFlip8  estoque_03                   8
14         Galaxy A17  estoque_03                  15

In [4]:
df_melt[['estoque', 'mes']] = df_melt['mes'].str.rsplit('_', n=1, expand=True)
df_melt

              produto mes  quantidade_estoque  estoque
0     Samsung ZFold 8  01                   8  estoque
1          Galaxy A57  01                  20  estoque
2   Samsung S26 Ultra  01                   5  estoque
3      Samsung ZFlip8  01                   8  estoque
4          Galaxy A17  01                  25  estoque
5     Samsung ZFold 8  02                   5  estoque
6          Galaxy A57  02                   3  estoque
7   Samsung S26 Ultra  02                   2  estoque
8      Samsung ZFlip8  02                   4  estoque
9          Galaxy A17  02                  10  estoque
10    Samsung ZFold 8  03                   6  estoque
11         Galaxy A57  03                  17  estoque
12  Samsung S26 Ultra  03                   3  estoque
13     Samsung ZFlip8  03                   8  estoque
14         Galaxy A17  03                  15  estoque

In [5]:
df_melt = df_melt.drop(columns=['estoque'])
df_melt

              produto mes  quantidade_estoque
0     Samsung ZFold 8  01                   8
1          Galaxy A57  01                  20
2   Samsung S26 Ultra  01                   5
3      Samsung ZFlip8  01                   8
4          Galaxy A17  01                  25
5     Samsung ZFold 8  02                   5
6          Galaxy A57  02                   3
7   Samsung S26 Ultra  02                   2
8      Samsung ZFlip8  02                   4
9          Galaxy A17  02                  10
10    Samsung ZFold 8  03                   6
11         Galaxy A57  03                  17
12  Samsung S26 Ultra  03                   3
13     Samsung ZFlip8  03                   8
14         Galaxy A17  03                  15

In [6]:
df_melt.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   produto             15 non-null     str
 1   mes                 15 non-null     str
 2   quantidade_estoque  15 non-null     int64
dtypes: int64(1), str(2)
memory usage: 492.0 bytes

In [9]:
df_melt['mes'] = pd.to_datetime(df_melt['mes'], format='%m')
df_melt.info()
df_melt

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   produto             15 non-null     str
 1   mes                 15 non-null     datetime64[us]
 2   quantidade_estoque  15 non-null     int64
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 492.0 bytes

              produto        mes  quantidade_estoque
0     Samsung ZFold 8 1900-01-01                   8
1          Galaxy A57 1900-01-01                  20
2   Samsung S26 Ultra 1900-01-01                   5
3      Samsung ZFlip8 1900-01-01                   8
4          Galaxy A17 1900-01-01                  25
5     Samsung ZFold 8 1900-02-01                   5
6          Galaxy A57 1900-02-01                   3
7   Samsung S26 Ultra 1900-02-01                   2
8      Samsung ZFlip8 1900-02-01                   4
9          Galaxy A17 1900-02-01                  10
10    Samsung ZFold 8 1900-03-01                   6
11         Galaxy A57 1900-03-01                  17
12  Samsung S26 Ultra 1900-03-01                   3
13     Samsung ZFlip8 1900-03-01                   8
14         Galaxy A17 1900-03-01                  15

In [11]:
df_melt['mes'] = df_melt['mes'].dt.month
df_melt

              produto  mes  quantidade_estoque
0     Samsung ZFold 8    1                   8
1          Galaxy A57    1                  20
2   Samsung S26 Ultra    1                   5
3      Samsung ZFlip8    1                   8
4          Galaxy A17    1                  25
5     Samsung ZFold 8    2                   5
6          Galaxy A57    2                   3
7   Samsung S26 Ultra    2                   2
8      Samsung ZFlip8    2                   4
9          Galaxy A17    2                  10
10    Samsung ZFold 8    3                   6
11         Galaxy A57    3                  17
12  Samsung S26 Ultra    3                   3
13     Samsung ZFlip8    3                   8
14         Galaxy A17    3                  15

In [12]:
df_pivot_table = df_melt.pivot_table(
    index=['produto'],
    columns=['mes'],
    values=['quantidade_estoque'],
    aggfunc='first'
)
df_pivot_table

                  quantidade_estoque
mes                                1   2   3
produto
Galaxy A17                        25  10  15
Galaxy A57                        20   3  17
Samsung S26 Ultra                  5   2   3
Samsung ZFlip8                     8   4   8
Samsung ZFold 8                    8   5   6