In [1]:
import pandas as pd

dados = {
    'pedidos_id':[1,2,3,4,5,6],
    'data_pedido':['01-05-2026','06-05-2026', '09-01-2026', '12-09-2026', '04-22-2026','06-21-2026' ]
}
df = pd.DataFrame(dados)
df

   pedidos_id data_pedido
0           1  01-05-2026
1           2  06-05-2026
2           3  09-01-2026
3           4  12-09-2026
4           5  04-22-2026
5           6  06-21-2026

In [2]:
df['data_pedido'] = pd.to_datetime(df['data_pedido'], errors='coerce')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pedidos_id   6 non-null      int64
 1   data_pedido  6 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(1)
memory usage: 228.0 bytes

In [4]:
df

   pedidos_id data_pedido
0           1  2026-01-05
1           2  2026-06-05
2           3  2026-09-01
3           4  2026-12-09
4           5  2026-04-22
5           6  2026-06-21

In [5]:
df['mes'] = df['data_pedido'].dt.month
df['dia'] = df['data_pedido'].dt.day_name()

In [6]:
df

   pedidos_id data_pedido  mes        dia
0           1  2026-01-05    1     Monday
1           2  2026-06-05    6     Friday
2           3  2026-09-01    9    Tuesday
3           4  2026-12-09   12  Wednesday
4           5  2026-04-22    4  Wednesday
5           6  2026-06-21    6     Sunday