In [1]:
from itertools import groupby

import pandas as pd

dados = {
    'pedido_id':[1,2,3,4,5,6,7,8,9,10],
    'data_pedido':[
        '05-22-2026', '05-12-2026', '11-30-2026', '11-22-2026',
        '10-21-2026', '10-12-2026', '06-02-2026',
        '07-20-2026', '08-14-2026', '05-21-2026'],
    'valor':[2000, 1000, 900, 7689, 2345,
             5003, 3267, 5612, 3109, 2000]
}

df = pd.DataFrame(dados)
df

   pedido_id data_pedido  valor
0          1  05-22-2026   2000
1          2  05-12-2026   1000
2          3  11-30-2026    900
3          4  11-22-2026   7689
4          5  10-21-2026   2345
5          6  10-12-2026   5003
6          7  06-02-2026   3267
7          8  07-20-2026   5612
8          9  08-14-2026   3109
9         10  05-21-2026   2000

In [2]:
df['data_pedido'] = pd.to_datetime(df['data_pedido'], format='%m-%d-%Y')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pedido_id    10 non-null     int64
 1   data_pedido  10 non-null     datetime64[us]
 2   valor        10 non-null     int64
dtypes: datetime64[us](1), int64(2)
memory usage: 372.0 bytes

In [4]:
df['mes'] = df['data_pedido'].dt.month

In [5]:
df

   pedido_id data_pedido  valor  mes
0          1  2026-05-22   2000    5
1          2  2026-05-12   1000    5
2          3  2026-11-30    900   11
3          4  2026-11-22   7689   11
4          5  2026-10-21   2345   10
5          6  2026-10-12   5003   10
6          7  2026-06-02   3267    6
7          8  2026-07-20   5612    7
8          9  2026-08-14   3109    8
9         10  2026-05-21   2000    5

In [8]:
df.groupby(['mes'])['valor'].sum()

mes
5     5000
6     3267
7     5612
8     3109
10    7348
11    8589
Name: valor, dtype: int64