In [ ]:
from parso import normalizer

"""
Tipo inteiro (int)
Ponto Flutuante ou Decimal (float)
String (str)
String (Object)
Data (datetime)
"""

In [2]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\ruans\OneDrive\Documentos\Material curso engenharia de dados\Python+-+SGBDS\Arquivos\05.+SQL+Server\05. SQL Server\Origem\Origem\arquivos_csv\Clientes.csv", delimiter=',')
df

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
...,...,...,...,...,...,...,...,...,...,...,...
95,95,2018-10-01 11:35:59,Mariana,Rosa,mariana@usuario.com,9 3139-2145,Brasil,NaN,NaN,NaN,NaN
96,96,2018-01-23 19:14:21,Paulo,Câmara,paulo@usuario.com,9 4785-1135,Brasil,Sergipe,Praça 73 do Estado Sergipe,219.0,Apto 6
97,97,2018-07-04 18:45:41,Marta,Góes,marta@teste.com,9 4102-4352,Brasil,Paraná,Rua 61 do Estado Paraná,402.0,Apto 24
98,98,2018-01-24 16:21:06,Cibele,Costa,cibele@meu_email.com,9 4211-6968,Brasil,Mato Grosso,Praça 75 do Estado Mato Grosso,24.0,NaN
99,99,2018-07-24 08:26:27,Jéssica,Jesus,jéssica@usuario.com,9 6100-1466,Brasil,Paraná,Avenida 19 do Estado Paraná,738.0,Conjunto 22

In [4]:
print(df['id'].dtype)

int64

In [7]:
print(df['created_at'].dtypes)
print(df['first_name'].dtypes)

str
str

In [8]:
for coluna in df.columns:
    print(f'coluna: {coluna}, Tipo de dados: {df[coluna].dtypes}')

coluna: id, Tipo de dados: int64
coluna: created_at, Tipo de dados: str
coluna: first_name, Tipo de dados: str
coluna: last_name, Tipo de dados: str
coluna: email, Tipo de dados: str
coluna: cell_phone, Tipo de dados: str
coluna: country, Tipo de dados: str
coluna: state, Tipo de dados: str
coluna: street, Tipo de dados: str
coluna: number, Tipo de dados: float64
coluna: additionals, Tipo de dados: str

Convertendo Dados

In [10]:
df['id'] = df['id'].astype(float)

In [12]:
print(df['id'].dtype)

float64

In [13]:
for coluna in df.columns:
    print(f'Coluna: {coluna}, Tipo de dado: {df[coluna].dtypes}')

Coluna: id, Tipo de dado: float64
Coluna: created_at, Tipo de dado: str
Coluna: first_name, Tipo de dado: str
Coluna: last_name, Tipo de dado: str
Coluna: email, Tipo de dado: str
Coluna: cell_phone, Tipo de dado: str
Coluna: country, Tipo de dado: str
Coluna: state, Tipo de dado: str
Coluna: street, Tipo de dado: str
Coluna: number, Tipo de dado: float64
Coluna: additionals, Tipo de dado: str

Conversao Datas

In [17]:
df = pd.read_csv(r"C:\Users\ruans\OneDrive\Documentos\Material curso engenharia de dados\Python+-+SGBDS\Arquivos\05.+SQL+Server\05. SQL Server\Origem\Origem\arquivos_csv\Clientes.csv", delimiter=',')
df

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
...,...,...,...,...,...,...,...,...,...,...,...
95,95,2018-10-01 11:35:59,Mariana,Rosa,mariana@usuario.com,9 3139-2145,Brasil,NaN,NaN,NaN,NaN
96,96,2018-01-23 19:14:21,Paulo,Câmara,paulo@usuario.com,9 4785-1135,Brasil,Sergipe,Praça 73 do Estado Sergipe,219.0,Apto 6
97,97,2018-07-04 18:45:41,Marta,Góes,marta@teste.com,9 4102-4352,Brasil,Paraná,Rua 61 do Estado Paraná,402.0,Apto 24
98,98,2018-01-24 16:21:06,Cibele,Costa,cibele@meu_email.com,9 4211-6968,Brasil,Mato Grosso,Praça 75 do Estado Mato Grosso,24.0,NaN
99,99,2018-07-24 08:26:27,Jéssica,Jesus,jéssica@usuario.com,9 6100-1466,Brasil,Paraná,Avenida 19 do Estado Paraná,738.0,Conjunto 22

In [4]:
print(df['created_at'].dtypes)

str

In [5]:
# Converter a coluna 'created_at' para o formato de data e hora
df['created_at'] = pd.to_datetime(df['created_at'])

In [6]:
print(df['created_at'].dtypes)

datetime64[us]

In [13]:
# Filtrar os dados para o intervalo de anos entre 2018 e 2020
df_filtrado = df[(df['created_at'].dt.year >= 2018) & (df['created_at'].dt.year <= 2020)]

df_filtrado.head()

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
5,5,2018-01-05 17:20:49,Marcelo,Barroso,NaN,9 2830-2088,Brasil,Rio Grande do Sul,Rua 28 do Estado Rio Grande do Sul,805.0,Conjunto 13
6,6,2018-06-18 11:17:42,Cristiano,Elísio,cristiano@exemplo.com,9 3532-8404,Brasil,Goiás,Rua 78 do Estado Goiás,877.0,Apto 14

In [14]:
# FIltrar somente o ano de 2018 e o mês de janeiro
df_dt2 = df[(df['created_at'].dt.year == 2018) & (df['created_at'].dt.month == 1)]


df_dt2.head()

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
5,5,2018-01-05 17:20:49,Marcelo,Barroso,NaN,9 2830-2088,Brasil,Rio Grande do Sul,Rua 28 do Estado Rio Grande do Sul,805.0,Conjunto 13
36,36,2018-01-26 03:29:13,Mariana,Góes,mariana@meu_email.com,9 7324-4293,Brasil,NaN,NaN,NaN,Apto 25
43,43,2018-01-07 07:54:22,Daniela,Lima,NaN,9 1763-2584,Brasil,Rio de Janeiro,NaN,NaN,Apto 20
54,54,2018-01-25 02:11:25,Diego,Teixeira,diego@exemplo.com,9 5247-1737,Brasil,Pará,Rua 8 do Estado Pará,722.0,Conjunto 16

In [36]:
df = pd.read_csv(r"C:\Users\ruans\OneDrive\Documentos\Material curso engenharia de dados\Python+-+SGBDS\Arquivos\05.+SQL+Server\05. SQL Server\Origem\Origem\arquivos_csv\Clientes.csv", delimiter=',')
df['created_at'] = pd.to_datetime(df['created_at'])

In [37]:
# Converter a coluna 'created_at' para o formato de data no padrão brasileiro
df['created_at'] = df['created_at'].dt.strftime('%d/%m/%Y')

In [38]:
df

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,01/11/2017,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16
1,1,16/10/2017,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,16/06/2018,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
3,3,17/01/2018,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
4,4,06/08/2018,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
...,...,...,...,...,...,...,...,...,...,...,...
95,95,01/10/2018,Mariana,Rosa,mariana@usuario.com,9 3139-2145,Brasil,NaN,NaN,NaN,NaN
96,96,23/01/2018,Paulo,Câmara,paulo@usuario.com,9 4785-1135,Brasil,Sergipe,Praça 73 do Estado Sergipe,219.0,Apto 6
97,97,04/07/2018,Marta,Góes,marta@teste.com,9 4102-4352,Brasil,Paraná,Rua 61 do Estado Paraná,402.0,Apto 24
98,98,24/01/2018,Cibele,Costa,cibele@meu_email.com,9 4211-6968,Brasil,Mato Grosso,Praça 75 do Estado Mato Grosso,24.0,NaN
99,99,24/07/2018,Jéssica,Jesus,jéssica@usuario.com,9 6100-1466,Brasil,Paraná,Avenida 19 do Estado Paraná,738.0,Conjunto 22

converter padrao BR no primeiro comando

In [39]:
import pandas as pd
df = pd.read_csv(r"C:\Users\ruans\OneDrive\Documentos\Material curso engenharia de dados\Python+-+SGBDS\Arquivos\05.+SQL+Server\05. SQL Server\Origem\Origem\arquivos_csv\Clientes.csv", delimiter=',')
df

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
...,...,...,...,...,...,...,...,...,...,...,...
95,95,2018-10-01 11:35:59,Mariana,Rosa,mariana@usuario.com,9 3139-2145,Brasil,NaN,NaN,NaN,NaN
96,96,2018-01-23 19:14:21,Paulo,Câmara,paulo@usuario.com,9 4785-1135,Brasil,Sergipe,Praça 73 do Estado Sergipe,219.0,Apto 6
97,97,2018-07-04 18:45:41,Marta,Góes,marta@teste.com,9 4102-4352,Brasil,Paraná,Rua 61 do Estado Paraná,402.0,Apto 24
98,98,2018-01-24 16:21:06,Cibele,Costa,cibele@meu_email.com,9 4211-6968,Brasil,Mato Grosso,Praça 75 do Estado Mato Grosso,24.0,NaN
99,99,2018-07-24 08:26:27,Jéssica,Jesus,jéssica@usuario.com,9 6100-1466,Brasil,Paraná,Avenida 19 do Estado Paraná,738.0,Conjunto 22

In [ ]:
# Converter a coluna 'created_at' em formato de data e hora
df['created_at'] = pd.to_datetime(df['created_at'])

In [40]:
#converter a data para o padrão brasileiro
data_brasil = '%d/%m/%Y %H:%M:%S'
df['created_at'] = df['created_at'].dt.strftime(data_brasil)
df

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,01/11/2017 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16
1,1,16/10/2017 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,16/06/2018 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
3,3,17/01/2018 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
4,4,06/08/2018 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
...,...,...,...,...,...,...,...,...,...,...,...
95,95,01/10/2018 11:35:59,Mariana,Rosa,mariana@usuario.com,9 3139-2145,Brasil,NaN,NaN,NaN,NaN
96,96,23/01/2018 19:14:21,Paulo,Câmara,paulo@usuario.com,9 4785-1135,Brasil,Sergipe,Praça 73 do Estado Sergipe,219.0,Apto 6
97,97,04/07/2018 18:45:41,Marta,Góes,marta@teste.com,9 4102-4352,Brasil,Paraná,Rua 61 do Estado Paraná,402.0,Apto 24
98,98,24/01/2018 16:21:06,Cibele,Costa,cibele@meu_email.com,9 4211-6968,Brasil,Mato Grosso,Praça 75 do Estado Mato Grosso,24.0,NaN
99,99,24/07/2018 08:26:27,Jéssica,Jesus,jéssica@usuario.com,9 6100-1466,Brasil,Paraná,Avenida 19 do Estado Paraná,738.0,Conjunto 22