In [1]:
import pandas as pd

from Exercícios.pivot_table_exercicios.pivot_table import df_pivot_table

report = {
    'campanha_id':[1,2,3,4,5,6,7,8],
    'canal':['Instagram', 'Google Ads', 'Email', 'Email',
             'TikTok', 'Google Ads', 'Instagram', 'Twitter'],
    'investimento_01-2024':[4500, 8500, 1200, 1800,
                            3500, 6500, 4000, 1800
                            ],
    'investimento_02-2024':[4800, 9200, 1200, 1900,
                            3800, 7000, 4200, 1700
                            ],
    'investimento_03-2024':[5200, 8800, 1100, 2000,
                            4200, 7200, 4500, 1900
                            ],
    'cliques_01-2024':[3200, 4100, 1800, 2400,
                       2900, 3500, 3800, 1600
                       ],
    'cliques_02-2024':[3500, 4500, 1950, 2550,
                       3100, 3800, 4000, 1750
                       ],
    'cliques_03-2024':[3700, 4300, 1700, 2700,
                       3400, 3900, 4200, 1850
                       ]
}

df = pd.DataFrame(report)
df

,campanha_id,canal,investimento_01-2024,investimento_02-2024,investimento_03-2024,cliques_01-2024,cliques_02-2024,cliques_03-2024
0,1,Instagram,4500,4800,5200,3200,3500,3700
1,2,Google Ads,8500,9200,8800,4100,4500,4300
2,3,Email,1200,1200,1100,1800,1950,1700
3,4,Email,1800,1900,2000,2400,2550,2700
4,5,TikTok,3500,3800,4200,2900,3100,3400
5,6,Google Ads,6500,7000,7200,3500,3800,3900
6,7,Instagram,4000,4200,4500,3800,4000,4200
7,8,Twitter,1800,1700,1900,1600,1750,1850

In [2]:
df_melt = df.melt(
    id_vars=['campanha_id', 'canal'],
    value_vars=[
        'investimento_01-2024','investimento_02-2024','investimento_03-2024', 'cliques_01-2024', 'cliques_02-2024', 'cliques_03-2024'
    ],
    var_name='metrica_mes',
    value_name='valor'
)
df_melt

    campanha_id       canal           metrica_mes  valor
0             1   Instagram  investimento_01-2024   4500
1             2  Google Ads  investimento_01-2024   8500
2             3       Email  investimento_01-2024   1200
3             4       Email  investimento_01-2024   1800
4             5      TikTok  investimento_01-2024   3500
5             6  Google Ads  investimento_01-2024   6500
6             7   Instagram  investimento_01-2024   4000
7             8     Twitter  investimento_01-2024   1800
8             1   Instagram  investimento_02-2024   4800
9             2  Google Ads  investimento_02-2024   9200
10            3       Email  investimento_02-2024   1200
11            4       Email  investimento_02-2024   1900
12            5      TikTok  investimento_02-2024   3800
13            6  Google Ads  investimento_02-2024   7000
14            7   Instagram  investimento_02-2024   4200
15            8     Twitter  investimento_02-2024   1700
16            1   Instagram  investimento_03-2024   5200
17            2  Google Ads  investimento_03-2024   8800
18            3       Email  investimento_03-2024   1100
19            4       Email  investimento_03-2024   2000
20            5      TikTok  investimento_03-2024   4200
21            6  Google Ads  investimento_03-2024   7200
22            7   Instagram  investimento_03-2024   4500
23            8     Twitter  investimento_03-2024   1900
24            1   Instagram       cliques_01-2024   3200
25            2  Google Ads       cliques_01-2024   4100
26            3       Email       cliques_01-2024   1800
27            4       Email       cliques_01-2024   2400
28            5      TikTok       cliques_01-2024   2900
29            6  Google Ads       cliques_01-2024   3500
30            7   Instagram       cliques_01-2024   3800
31            8     Twitter       cliques_01-2024   1600
32            1   Instagram       cliques_02-2024   3500
33            2  Google Ads       cliques_02-2024   4500
34            3       Email       cliques_02-2024   1950
35            4       Email       cliques_02-2024   2550
36            5      TikTok       cliques_02-2024   3100
37            6  Google Ads       cliques_02-2024   3800
38            7   Instagram       cliques_02-2024   4000
39            8     Twitter       cliques_02-2024   1750
40            1   Instagram       cliques_03-2024   3700
41            2  Google Ads       cliques_03-2024   4300
42            3       Email       cliques_03-2024   1700
43            4       Email       cliques_03-2024   2700
44            5      TikTok       cliques_03-2024   3400
45            6  Google Ads       cliques_03-2024   3900
46            7   Instagram       cliques_03-2024   4200
47            8     Twitter       cliques_03-2024   1850

In [3]:
df_melt[['metrica','mes']] = df_melt['metrica_mes'].str.rsplit('_', n=1, expand=True)
df_melt

,campanha_id,canal,metrica_mes,valor,metrica,mes
0,1,Instagram,investimento_01-2024,4500,investimento,01-2024
1,2,Google Ads,investimento_01-2024,8500,investimento,01-2024
2,3,Email,investimento_01-2024,1200,investimento,01-2024
3,4,Email,investimento_01-2024,1800,investimento,01-2024
4,5,TikTok,investimento_01-2024,3500,investimento,01-2024
5,6,Google Ads,investimento_01-2024,6500,investimento,01-2024
6,7,Instagram,investimento_01-2024,4000,investimento,01-2024
7,8,Twitter,investimento_01-2024,1800,investimento,01-2024
8,1,Instagram,investimento_02-2024,4800,investimento,02-2024
9,2,Google Ads,investimento_02-2024,9200,investimento,02-2024
10,3,Email,investimento_02-2024,1200,investimento,02-2024
11,4,Email,investimento_02-2024,1900,investimento,02-2024
12,5,TikTok,investimento_02-2024,3800,investimento,02-2024
13,6,Google Ads,investimento_02-2024,7000,investimento,02-2024
14,7,Instagram,investimento_02-2024,4200,investimento,02-2024
15,8,Twitter,investimento_02-2024,1700,investimento,02-2024
16,1,Instagram,investimento_03-2024,5200,investimento,03-2024
17,2,Google Ads,investimento_03-2024,8800,investimento,03-2024
18,3,Email,investimento_03-2024,1100,investimento,03-2024
19,4,Email,investimento_03-2024,2000,investimento,03-2024
20,5,TikTok,investimento_03-2024,4200,investimento,03-2024
21,6,Google Ads,investimento_03-2024,7200,investimento,03-2024
22,7,Instagram,investimento_03-2024,4500,investimento,03-2024
23,8,Twitter,investimento_03-2024,1900,investimento,03-2024
24,1,Instagram,cliques_01-2024,3200,cliques,01-2024
25,2,Google Ads,cliques_01-2024,4100,cliques,01-2024
26,3,Email,cliques_01-2024,1800,cliques,01-2024
27,4,Email,cliques_01-2024,2400,cliques,01-2024
28,5,TikTok,cliques_01-2024,2900,cliques,01-2024
29,6,Google Ads,cliques_01-2024,3500,cliques,01-2024
30,7,Instagram,cliques_01-2024,3800,cliques,01-2024
31,8,Twitter,cliques_01-2024,1600,cliques,01-2024
32,1,Instagram,cliques_02-2024,3500,cliques,02-2024
33,2,Google Ads,cliques_02-2024,4500,cliques,02-2024
34,3,Email,cliques_02-2024,1950,cliques,02-2024
35,4,Email,cliques_02-2024,2550,cliques,02-2024
36,5,TikTok,cliques_02-2024,3100,cliques,02-2024
37,6,Google Ads,cliques_02-2024,3800,cliques,02-2024
38,7,Instagram,cliques_02-2024,4000,cliques,02-2024
39,8,Twitter,cliques_02-2024,1750,cliques,02-2024
40,1,Instagram,cliques_03-2024,3700,cliques,03-2024
41,2,Google Ads,cliques_03-2024,4300,cliques,03-2024
42,3,Email,cliques_03-2024,1700,cliques,03-2024
43,4,Email,cliques_03-2024,2700,cliques,03-2024
44,5,TikTok,cliques_03-2024,3400,cliques,03-2024
45,6,Google Ads,cliques_03-2024,3900,cliques,03-2024
46,7,Instagram,cliques_03-2024,4200,cliques,03-2024
47,8,Twitter,cliques_03-2024,1850,cliques,03-2024

In [4]:
df_melt = df_melt.drop(columns= 'metrica_mes')

In [5]:
df_melt

    campanha_id       canal  valor       metrica      mes
0             1   Instagram   4500  investimento  01-2024
1             2  Google Ads   8500  investimento  01-2024
2             3       Email   1200  investimento  01-2024
3             4       Email   1800  investimento  01-2024
4             5      TikTok   3500  investimento  01-2024
5             6  Google Ads   6500  investimento  01-2024
6             7   Instagram   4000  investimento  01-2024
7             8     Twitter   1800  investimento  01-2024
8             1   Instagram   4800  investimento  02-2024
9             2  Google Ads   9200  investimento  02-2024
10            3       Email   1200  investimento  02-2024
11            4       Email   1900  investimento  02-2024
12            5      TikTok   3800  investimento  02-2024
13            6  Google Ads   7000  investimento  02-2024
14            7   Instagram   4200  investimento  02-2024
15            8     Twitter   1700  investimento  02-2024
16            1   Instagram   5200  investimento  03-2024
17            2  Google Ads   8800  investimento  03-2024
18            3       Email   1100  investimento  03-2024
19            4       Email   2000  investimento  03-2024
20            5      TikTok   4200  investimento  03-2024
21            6  Google Ads   7200  investimento  03-2024
22            7   Instagram   4500  investimento  03-2024
23            8     Twitter   1900  investimento  03-2024
24            1   Instagram   3200       cliques  01-2024
25            2  Google Ads   4100       cliques  01-2024
26            3       Email   1800       cliques  01-2024
27            4       Email   2400       cliques  01-2024
28            5      TikTok   2900       cliques  01-2024
29            6  Google Ads   3500       cliques  01-2024
30            7   Instagram   3800       cliques  01-2024
31            8     Twitter   1600       cliques  01-2024
32            1   Instagram   3500       cliques  02-2024
33            2  Google Ads   4500       cliques  02-2024
34            3       Email   1950       cliques  02-2024
35            4       Email   2550       cliques  02-2024
36            5      TikTok   3100       cliques  02-2024
37            6  Google Ads   3800       cliques  02-2024
38            7   Instagram   4000       cliques  02-2024
39            8     Twitter   1750       cliques  02-2024
40            1   Instagram   3700       cliques  03-2024
41            2  Google Ads   4300       cliques  03-2024
42            3       Email   1700       cliques  03-2024
43            4       Email   2700       cliques  03-2024
44            5      TikTok   3400       cliques  03-2024
45            6  Google Ads   3900       cliques  03-2024
46            7   Instagram   4200       cliques  03-2024
47            8     Twitter   1850       cliques  03-2024

In [6]:
df_melt['mes'] = pd.to_datetime(df_melt['mes'], format='%m-%Y')
df_melt

    campanha_id       canal  valor       metrica        mes
0             1   Instagram   4500  investimento 2024-01-01
1             2  Google Ads   8500  investimento 2024-01-01
2             3       Email   1200  investimento 2024-01-01
3             4       Email   1800  investimento 2024-01-01
4             5      TikTok   3500  investimento 2024-01-01
5             6  Google Ads   6500  investimento 2024-01-01
6             7   Instagram   4000  investimento 2024-01-01
7             8     Twitter   1800  investimento 2024-01-01
8             1   Instagram   4800  investimento 2024-02-01
9             2  Google Ads   9200  investimento 2024-02-01
10            3       Email   1200  investimento 2024-02-01
11            4       Email   1900  investimento 2024-02-01
12            5      TikTok   3800  investimento 2024-02-01
13            6  Google Ads   7000  investimento 2024-02-01
14            7   Instagram   4200  investimento 2024-02-01
15            8     Twitter   1700  investimento 2024-02-01
16            1   Instagram   5200  investimento 2024-03-01
17            2  Google Ads   8800  investimento 2024-03-01
18            3       Email   1100  investimento 2024-03-01
19            4       Email   2000  investimento 2024-03-01
20            5      TikTok   4200  investimento 2024-03-01
21            6  Google Ads   7200  investimento 2024-03-01
22            7   Instagram   4500  investimento 2024-03-01
23            8     Twitter   1900  investimento 2024-03-01
24            1   Instagram   3200       cliques 2024-01-01
25            2  Google Ads   4100       cliques 2024-01-01
26            3       Email   1800       cliques 2024-01-01
27            4       Email   2400       cliques 2024-01-01
28            5      TikTok   2900       cliques 2024-01-01
29            6  Google Ads   3500       cliques 2024-01-01
30            7   Instagram   3800       cliques 2024-01-01
31            8     Twitter   1600       cliques 2024-01-01
32            1   Instagram   3500       cliques 2024-02-01
33            2  Google Ads   4500       cliques 2024-02-01
34            3       Email   1950       cliques 2024-02-01
35            4       Email   2550       cliques 2024-02-01
36            5      TikTok   3100       cliques 2024-02-01
37            6  Google Ads   3800       cliques 2024-02-01
38            7   Instagram   4000       cliques 2024-02-01
39            8     Twitter   1750       cliques 2024-02-01
40            1   Instagram   3700       cliques 2024-03-01
41            2  Google Ads   4300       cliques 2024-03-01
42            3       Email   1700       cliques 2024-03-01
43            4       Email   2700       cliques 2024-03-01
44            5      TikTok   3400       cliques 2024-03-01
45            6  Google Ads   3900       cliques 2024-03-01
46            7   Instagram   4200       cliques 2024-03-01
47            8     Twitter   1850       cliques 2024-03-01

In [7]:
df_melt['mes'] = df_melt['mes'].dt.month
df_melt

    campanha_id       canal  valor       metrica  mes
0             1   Instagram   4500  investimento    1
1             2  Google Ads   8500  investimento    1
2             3       Email   1200  investimento    1
3             4       Email   1800  investimento    1
4             5      TikTok   3500  investimento    1
5             6  Google Ads   6500  investimento    1
6             7   Instagram   4000  investimento    1
7             8     Twitter   1800  investimento    1
8             1   Instagram   4800  investimento    2
9             2  Google Ads   9200  investimento    2
10            3       Email   1200  investimento    2
11            4       Email   1900  investimento    2
12            5      TikTok   3800  investimento    2
13            6  Google Ads   7000  investimento    2
14            7   Instagram   4200  investimento    2
15            8     Twitter   1700  investimento    2
16            1   Instagram   5200  investimento    3
17            2  Google Ads   8800  investimento    3
18            3       Email   1100  investimento    3
19            4       Email   2000  investimento    3
20            5      TikTok   4200  investimento    3
21            6  Google Ads   7200  investimento    3
22            7   Instagram   4500  investimento    3
23            8     Twitter   1900  investimento    3
24            1   Instagram   3200       cliques    1
25            2  Google Ads   4100       cliques    1
26            3       Email   1800       cliques    1
27            4       Email   2400       cliques    1
28            5      TikTok   2900       cliques    1
29            6  Google Ads   3500       cliques    1
30            7   Instagram   3800       cliques    1
31            8     Twitter   1600       cliques    1
32            1   Instagram   3500       cliques    2
33            2  Google Ads   4500       cliques    2
34            3       Email   1950       cliques    2
35            4       Email   2550       cliques    2
36            5      TikTok   3100       cliques    2
37            6  Google Ads   3800       cliques    2
38            7   Instagram   4000       cliques    2
39            8     Twitter   1750       cliques    2
40            1   Instagram   3700       cliques    3
41            2  Google Ads   4300       cliques    3
42            3       Email   1700       cliques    3
43            4       Email   2700       cliques    3
44            5      TikTok   3400       cliques    3
45            6  Google Ads   3900       cliques    3
46            7   Instagram   4200       cliques    3
47            8     Twitter   1850       cliques    3

In [8]:
df_pivot_table = df_melt.pivot_table(
    index=['campanha_id', 'canal', 'mes'],
    columns=['metrica'],
    values=['valor'],
    aggfunc='first'
)
df_pivot_table

                             valor
metrica                    cliques investimento
campanha_id canal      mes
1           Instagram  1      3200         4500
                       2      3500         4800
                       3      3700         5200
2           Google Ads 1      4100         8500
                       2      4500         9200
                       3      4300         8800
3           Email      1      1800         1200
                       2      1950         1200
                       3      1700         1100
4           Email      1      2400         1800
                       2      2550         1900
                       3      2700         2000
5           TikTok     1      2900         3500
                       2      3100         3800
                       3      3400         4200
6           Google Ads 1      3500         6500
                       2      3800         7000
                       3      3900         7200
7           Instagram  1      3800         4000
                       2      4000         4200
                       3      4200         4500
8           Twitter    1      1600         1800
                       2      1750         1700
                       3      1850         1900

In [9]:
df_pivot_table['custo_por_cliques'] = df_pivot_table['valor']['investimento'] / df_pivot_table['valor']['cliques']
df_pivot_table

                             valor              custo_por_cliques
metrica                    cliques investimento
campanha_id canal      mes
1           Instagram  1      3200         4500          1.406250
                       2      3500         4800          1.371429
                       3      3700         5200          1.405405
2           Google Ads 1      4100         8500          2.073171
                       2      4500         9200          2.044444
                       3      4300         8800          2.046512
3           Email      1      1800         1200          0.666667
                       2      1950         1200          0.615385
                       3      1700         1100          0.647059
4           Email      1      2400         1800          0.750000
                       2      2550         1900          0.745098
                       3      2700         2000          0.740741
5           TikTok     1      2900         3500          1.206897
                       2      3100         3800          1.225806
                       3      3400         4200          1.235294
6           Google Ads 1      3500         6500          1.857143
                       2      3800         7000          1.842105
                       3      3900         7200          1.846154
7           Instagram  1      3800         4000          1.052632
                       2      4000         4200          1.050000
                       3      4200         4500          1.071429
8           Twitter    1      1600         1800          1.125000
                       2      1750         1700          0.971429
                       3      1850         1900          1.027027

In [10]:
df_pivot_table['custo_por_cliques'] = df_pivot_table['custo_por_cliques'].round(2)
df_pivot_table

                             valor              custo_por_cliques
metrica                    cliques investimento
campanha_id canal      mes
1           Instagram  1      3200         4500              1.41
                       2      3500         4800              1.37
                       3      3700         5200              1.41
2           Google Ads 1      4100         8500              2.07
                       2      4500         9200              2.04
                       3      4300         8800              2.05
3           Email      1      1800         1200              0.67
                       2      1950         1200              0.62
                       3      1700         1100              0.65
4           Email      1      2400         1800              0.75
                       2      2550         1900              0.75
                       3      2700         2000              0.74
5           TikTok     1      2900         3500              1.21
                       2      3100         3800              1.23
                       3      3400         4200              1.24
6           Google Ads 1      3500         6500              1.86
                       2      3800         7000              1.84
                       3      3900         7200              1.85
7           Instagram  1      3800         4000              1.05
                       2      4000         4200              1.05
                       3      4200         4500              1.07
8           Twitter    1      1600         1800              1.12
                       2      1750         1700              0.97
                       3      1850         1900              1.03

In [13]:
custo_esperado = 1.50
filtro = df_pivot_table[df_pivot_table['custo_por_cliques'] > custo_esperado]
filtro

                             valor              custo_por_cliques
metrica                    cliques investimento
campanha_id canal      mes
2           Google Ads 1      4100         8500              2.07
                       2      4500         9200              2.04
                       3      4300         8800              2.05
6           Google Ads 1      3500         6500              1.86
                       2      3800         7000              1.84
                       3      3900         7200              1.85