In [ ]:
import pandas as pd

In [3]:
base = './dados/dados_satisfacao.csv'
dados = pd.read_csv(base)

In [4]:
dados

,cliente_id,satisfacao_geral_01-2024,satisfacao_geral_02-2024,satisfacao_geral_03-2024,satisfacao_produto_01-2024,satisfacao_produto_02-2024,satisfacao_produto_03-2024,satisfacao_servico_01-2024,satisfacao_servico_02-2024,satisfacao_servico_03-2024,idade,genero
0,1,4,3,4,5,4,4,3,4,4,25,F
1,2,5,2,4,4,5,4,4,2,4,35,M
2,3,3,1,3,4,3,5,3,2,5,45,F
3,4,4,4,5,3,5,5,4,5,3,28,M
4,5,4,4,4,4,3,4,3,4,4,38,F
5,6,5,2,4,4,4,5,5,4,5,48,M
6,7,3,4,5,5,4,4,4,5,4,30,F
7,8,4,4,3,4,5,3,5,4,4,40,M
8,9,5,3,4,5,4,4,4,3,5,50,F
9,10,3,4,5,4,3,5,2,3,4,32,M

In [5]:
dados_melt = pd.melt(
    dados,
    id_vars=['cliente_id', 'idade', 'genero'], # Colunas que não vamos mexer
    value_vars=[
        'satisfacao_geral_01-2024',
        'satisfacao_geral_02-2024',
        'satisfacao_produto_01-2024',
        'satisfacao_produto_02-2024',
        'satisfacao_produto_03-2024',
        'satisfacao_servico_01-2024',
        'satisfacao_servico_02-2024',
        'satisfacao_servico_03-2024'
    ], #Colunas de onde irão vir os nossos valores
    var_name='categoria_mes', #É o nome dessa nova coluna que tera como linhas as colunas de value_vars
    value_name='nota' #Nome da coluna onde ira vir os valores
)

dados_melt

    cliente_id  idade genero               categoria_mes  nota
0            1     25      F    satisfacao_geral_01-2024     4
1            2     35      M    satisfacao_geral_01-2024     5
2            3     45      F    satisfacao_geral_01-2024     3
3            4     28      M    satisfacao_geral_01-2024     4
4            5     38      F    satisfacao_geral_01-2024     4
..         ...    ...    ...                         ...   ...
75           6     48      M  satisfacao_servico_03-2024     5
76           7     30      F  satisfacao_servico_03-2024     4
77           8     40      M  satisfacao_servico_03-2024     4
78           9     50      F  satisfacao_servico_03-2024     5
79          10     32      M  satisfacao_servico_03-2024     4

[80 rows x 5 columns]

Separando coluna categoria e mes

In [8]:
#Exemplo de split
'Ruan Santos'.split()

['Ruan', 'Santos']

In [10]:
dados_melt[['categoria', 'mes']] = dados_melt['categoria_mes'].str.rsplit('_', n=1, expand=True)

In [13]:
dados_melt

    cliente_id  idade genero  nota           categoria      mes
0            1     25      F     4    satisfacao_geral  01-2024
1            2     35      M     5    satisfacao_geral  01-2024
2            3     45      F     3    satisfacao_geral  01-2024
3            4     28      M     4    satisfacao_geral  01-2024
4            5     38      F     4    satisfacao_geral  01-2024
..         ...    ...    ...   ...                 ...      ...
75           6     48      M     5  satisfacao_servico  03-2024
76           7     30      F     4  satisfacao_servico  03-2024
77           8     40      M     4  satisfacao_servico  03-2024
78           9     50      F     5  satisfacao_servico  03-2024
79          10     32      M     4  satisfacao_servico  03-2024

[80 rows x 6 columns]

In [12]:
dados_melt = dados_melt.drop(columns=['categoria_mes'])

Conversão mes

In [15]:
dados_melt['mes'] = pd.to_datetime(dados_melt['mes'],format='%m-%Y')

dados_melt

    cliente_id  idade genero  nota           categoria        mes
0            1     25      F     4    satisfacao_geral 2024-01-01
1            2     35      M     5    satisfacao_geral 2024-01-01
2            3     45      F     3    satisfacao_geral 2024-01-01
3            4     28      M     4    satisfacao_geral 2024-01-01
4            5     38      F     4    satisfacao_geral 2024-01-01
..         ...    ...    ...   ...                 ...        ...
75           6     48      M     5  satisfacao_servico 2024-03-01
76           7     30      F     4  satisfacao_servico 2024-03-01
77           8     40      M     4  satisfacao_servico 2024-03-01
78           9     50      F     5  satisfacao_servico 2024-03-01
79          10     32      M     4  satisfacao_servico 2024-03-01

[80 rows x 6 columns]

In [16]:
dados_melt.info()

<class 'pandas.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cliente_id  80 non-null     int64
 1   idade       80 non-null     int64
 2   genero      80 non-null     str
 3   nota        80 non-null     int64
 4   categoria   80 non-null     str
 5   mes         80 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(3), str(2)
memory usage: 3.9 KB

In [17]:
dados_melt['mes'] = dados_melt['mes'].dt.month

dados_melt

    cliente_id  idade genero  nota           categoria  mes
0            1     25      F     4    satisfacao_geral    1
1            2     35      M     5    satisfacao_geral    1
2            3     45      F     3    satisfacao_geral    1
3            4     28      M     4    satisfacao_geral    1
4            5     38      F     4    satisfacao_geral    1
..         ...    ...    ...   ...                 ...  ...
75           6     48      M     5  satisfacao_servico    3
76           7     30      F     4  satisfacao_servico    3
77           8     40      M     4  satisfacao_servico    3
78           9     50      F     5  satisfacao_servico    3
79          10     32      M     4  satisfacao_servico    3

[80 rows x 6 columns]

In [18]:
dados_melt.info()

<class 'pandas.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cliente_id  80 non-null     int64
 1   idade       80 non-null     int64
 2   genero      80 non-null     str
 3   nota        80 non-null     int64
 4   categoria   80 non-null     str
 5   mes         80 non-null     int32
dtypes: int32(1), int64(3), str(2)
memory usage: 3.6 KB

In [19]:
dados_melt['genero'] = dados_melt['genero'].astype('category')
dados_melt['categoria'] = dados_melt['categoria'].astype('category')

In [20]:
dados_melt.info()

<class 'pandas.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cliente_id  80 non-null     int64
 1   idade       80 non-null     int64
 2   genero      80 non-null     category
 3   nota        80 non-null     int64
 4   categoria   80 non-null     category
 5   mes         80 non-null     int32
dtypes: category(2), int32(1), int64(3)
memory usage: 2.5 KB

In [21]:
dados_melt.groupby(['categoria', 'mes'])['nota'].mean()

categoria           mes
satisfacao_geral    1      4.0
                    2      3.1
satisfacao_produto  1      4.2
                    2      4.0
                    3      4.3
satisfacao_servico  1      3.7
                    2      3.6
                    3      4.2
Name: nota, dtype: float64

In [22]:
dados_melt.groupby(['categoria', 'mes'])['nota'].describe()

                        count  mean       std  min   25%  50%   75%  max
categoria          mes
satisfacao_geral   1     10.0   4.0  0.816497  3.0  3.25  4.0  4.75  5.0
                   2     10.0   3.1  1.100505  1.0  2.25  3.5  4.00  4.0
satisfacao_produto 1     10.0   4.2  0.632456  3.0  4.00  4.0  4.75  5.0
                   2     10.0   4.0  0.816497  3.0  3.25  4.0  4.75  5.0
                   3     10.0   4.3  0.674949  3.0  4.00  4.0  5.00  5.0
satisfacao_servico 1     10.0   3.7  0.948683  2.0  3.00  4.0  4.00  5.0
                   2     10.0   3.6  1.074968  2.0  3.00  4.0  4.00  5.0
                   3     10.0   4.2  0.632456  3.0  4.00  4.0  4.75  5.0