In [1]:
import pandas as pd
report = {
    'produto':['Iphone 18 Pro Max', 'Iphone Duo', 'Mesa', 'Cheetos', 'Sofa', 'Iphone 16 Pro Max', 'Iphone 16 pro', 'Iphone 16 Pro Max', 'Iphone 18 Pro Max', 'Iphone Duo'],
    'categoria':['Tecnologia', 'Tecnologia', 'Movel', 'Alimento', 'Movel',
                 'Tecnologia', 'Tecnologia', 'Tecnologia', 'Tecnologia', 'Tecnologia'],
    'quantidade':[1, 1, 2, 10, 2, 1, 1, 1, 1, 1],
    'preco_unitario':[13000, 22000, 700, 12.90, 1500, 7000, 5000, 7589, 12000, 19886],
    'data_venda':['2026-01-10', '2026-01-13', '2026-01-30', '2026-12-01', '2026-11-30', '2026-05-02', '2026-07-08', '2026-06-05', '2026-09-20', '2026-09-28']

}
df = pd.DataFrame(report)
df

             produto   categoria  quantidade  preco_unitario  data_venda
0  Iphone 18 Pro Max  Tecnologia           1         13000.0  2026-01-10
1         Iphone Duo  Tecnologia           1         22000.0  2026-01-13
2               Mesa       Movel           2           700.0  2026-01-30
3            Cheetos    Alimento          10            12.9  2026-12-01
4               Sofa       Movel           2          1500.0  2026-11-30
5  Iphone 16 Pro Max  Tecnologia           1          7000.0  2026-05-02
6      Iphone 16 pro  Tecnologia           1          5000.0  2026-07-08
7  Iphone 16 Pro Max  Tecnologia           1          7589.0  2026-06-05
8  Iphone 18 Pro Max  Tecnologia           1         12000.0  2026-09-20
9         Iphone Duo  Tecnologia           1         19886.0  2026-09-28

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   produto         10 non-null     str
 1   categoria       10 non-null     str
 2   quantidade      10 non-null     int64
 3   preco_unitario  10 non-null     float64
 4   data_venda      10 non-null     str
dtypes: float64(1), int64(1), str(3)
memory usage: 532.0 bytes

In [3]:
df['valor_total'] = df['quantidade'] * df['preco_unitario']
df

,produto,categoria,quantidade,preco_unitario,data_venda,valor_total
0,Iphone 18 Pro Max,Tecnologia,1,13000.0,2026-01-10,13000.0
1,Iphone Duo,Tecnologia,1,22000.0,2026-01-13,22000.0
2,Mesa,Movel,2,700.0,2026-01-30,1400.0
3,Cheetos,Alimento,10,12.9,2026-12-01,129.0
4,Sofa,Movel,2,1500.0,2026-11-30,3000.0
5,Iphone 16 Pro Max,Tecnologia,1,7000.0,2026-05-02,7000.0
6,Iphone 16 pro,Tecnologia,1,5000.0,2026-07-08,5000.0
7,Iphone 16 Pro Max,Tecnologia,1,7589.0,2026-06-05,7589.0
8,Iphone 18 Pro Max,Tecnologia,1,12000.0,2026-09-20,12000.0
9,Iphone Duo,Tecnologia,1,19886.0,2026-09-28,19886.0

In [4]:
maior_faturamento = df[df['valor_total'] == df['valor_total'].max()]
maior_faturamento

      produto   categoria  quantidade  preco_unitario  data_venda  valor_total
1  Iphone Duo  Tecnologia           1         22000.0  2026-01-13      22000.0

In [5]:
df_groupby = df.groupby(['categoria'])['valor_total'].sum()
df_groupby

categoria
Alimento        129.0
Movel          4400.0
Tecnologia    86475.0
Name: valor_total, dtype: float64

In [6]:
df['data_venda'] = pd.to_datetime(df['data_venda'], format='%Y-%m-%d')

In [7]:
df['mes'] = df['data_venda'].dt.month

In [10]:
maior_faturamento_mes = df.groupby(['mes'])['valor_total'].sum()
maior_faturamento_mes.idxmax()

np.int32(1)