In [1]:
import pandas as pd

report = {
    'funcionario':['Ronald', 'Luiz', 'Fabio',
                   'Claudio', 'Laura', 'Fernanda'],
    'departamento':['Tecnologia', 'Tecnologia', 'Financeiro',
                    'Administrativo', 'RH', 'RH'],
    'salario':[6000, 12000, 14000, 9452, 2554, 1946]
}
df = pd.DataFrame(report)
df

  funcionario    departamento  salario
0      Ronald      Tecnologia     6000
1        Luiz      Tecnologia    12000
2       Fabio      Financeiro    14000
3     Claudio  Administrativo     9452
4       Laura              RH     2554
5    Fernanda              RH     1946

In [2]:
def faixa_salarial(salario):
    if salario <= 3000:
        return 'baixo'
    elif(salario >= 3000) and (salario <= 6000):
        return 'médio'
    else:
        return 'alto'

In [3]:
dados_agrupados = df.groupby('departamento')['salario'].mean()
df_groupby = pd.DataFrame(dados_agrupados)
df_groupby

                salario
departamento
Administrativo   9452.0
Financeiro      14000.0
RH               2250.0
Tecnologia       9000.0

In [4]:
df['faixa_salarial'] = df['salario'].apply(faixa_salarial)
df

  funcionario    departamento  salario faixa_salarial
0      Ronald      Tecnologia     6000          médio
1        Luiz      Tecnologia    12000           alto
2       Fabio      Financeiro    14000           alto
3     Claudio  Administrativo     9452           alto
4       Laura              RH     2554          baixo
5    Fernanda              RH     1946          baixo