In [1]:
import pandas as pd
from pandas.core.dtypes import astype

df = pd.DataFrame({
    'register':[
        'João-25-SP',
        'Maria-17-RJ',
        'Pedro-32-MG',
        'Ana-8-BA',
        'Carlos-45-PR'
    ]
})

In [2]:
df

       register
0    João-25-SP
1   Maria-17-RJ
2   Pedro-32-MG
3      Ana-8-BA
4  Carlos-45-PR

In [3]:
def classificar_pessoa(register):
    classification = register.split('-')
    name = classification[0]
    age = classification[1]
    state = classification[2]
    age = int(age)
    if age < 12:
        age = f'{name} é Criança ({state})'
    elif age >= 12 and age <= 17:
        age = f'{name} é Adolescente ({state})'
    else:
        age = f'{name} é Adulto ({state})'
    return age

In [4]:
df['resumo'] = df['register'].apply(classificar_pessoa)

In [5]:
df

       register                    resumo
0    João-25-SP        João é Adulto (SP)
1   Maria-17-RJ  Maria é Adolescente (RJ)
2   Pedro-32-MG       Pedro é Adulto (MG)
3      Ana-8-BA        Ana é Criança (BA)
4  Carlos-45-PR      Carlos é Adulto (PR)