Reshaping

In [1]:
import pandas as pd

df = pd.read_excel("dados/reshaping.xlsx")

df

   Estudante Categoria  Semana          Tópico  Nota
0      Maria    Testes       1       1. Python   100
1      Maria   Projeto       1       1. Python   100
2      Maria    Testes       1       2. GitHub    70
3      Maria   Projeto       1       2. GitHub    70
4      Maria    Testes       2   3. Matplotlib    80
5      Maria   Projeto       2   3. Matplotlib    70
6      Maria    Testes       2          4. SQL    80
7      Maria   Projeto       2          4. SQL    70
8      Maria    Testes       3        5. NumPy    60
9      Maria   Projeto       3        5. NumPy    60
10     Maria    Testes       3          6. POO    90
11     Maria   Projeto       3          6. POO    80
12     Maria    Testes       4       7. Pandas    70
13     Maria   Projeto       4       7. Pandas    70
14     Maria    Testes       4  8. Estatística    80
15     Maria   Projeto       4  8. Estatística    80
16      João    Testes       1       1. Python   100
17      João   Projeto       1       1. Python    80
18      João    Testes       1       2. GitHub    90
19      João   Projeto       1       2. GitHub    90
20      João    Testes       2   3. Matplotlib    60
21      João   Projeto       2   3. Matplotlib    70
22      João    Testes       2          4. SQL    70
23      João   Projeto       2          4. SQL    80
24      João    Testes       3        5. NumPy    80
25      João   Projeto       3        5. NumPy    90
26      João    Testes       3          6. POO    70
27      João   Projeto       3          6. POO    80
28      João    Testes       4       7. Pandas    70
29      João   Projeto       4       7. Pandas   100
30      João    Testes       4  8. Estatística    80
31      João   Projeto       4  8. Estatística    90

In [2]:
df.index

RangeIndex(start=0, stop=32, step=1)

In [3]:
df.columns

Index(['Estudante', 'Categoria', 'Semana', 'Tópico', 'Nota'], dtype='str')

Metodo Pivot

In [4]:
df_pivot = df.pivot(
    index=['Estudante'],
    columns=['Categoria', 'Semana', 'Tópico'],
    values=['Nota']
)

In [10]:
df_pivot

               Nota                                                            \
Categoria    Testes   Projeto    Testes   Projeto        Testes       Projeto
Semana            1         1         1         1             2             2
Tópico    1. Python 1. Python 2. GitHub 2. GitHub 3. Matplotlib 3. Matplotlib
Estudante
João            100        80        90        90            60            70
Maria           100       100        70        70            80            70

                                                                               \
Categoria Testes Projeto   Testes  Projeto Testes Projeto    Testes   Projeto
Semana         2       2        3        3      3       3         4         4
Tópico    4. SQL  4. SQL 5. NumPy 5. NumPy 6. POO  6. POO 7. Pandas 7. Pandas
Estudante
João          70      80       80       90     70      80        70       100
Maria         80      70       60       60     90      80        70        70


Categoria         Testes        Projeto
Semana                 4              4
Tópico    8. Estatística 8. Estatística
Estudante
João                  80             90
Maria                 80             80

In [ ]:
df_pivot.index

In [ ]:
df_pivot.columns

Stack

In [14]:
df_pivot.stack(level=1)

                         Nota                                                 \
Semana                      1                       2               3
Tópico              1. Python 2. GitHub 3. Matplotlib 4. SQL 5. NumPy 6. POO
Estudante Categoria
João      Testes          100        90            60     70       80     70
          Projeto          80        90            70     80       90     80
Maria     Testes          100        70            80     80       60     90
          Projeto         100        70            70     70       60     80


Semana                      4
Tópico              7. Pandas 8. Estatística
Estudante Categoria
João      Testes           70             80
          Projeto         100             90
Maria     Testes           70             80
          Projeto          70             80

Unstack

In [15]:
df_pivot.stack(level=1).unstack()

               Nota                                                         \
Semana            1                                       2
Tópico    1. Python         2. GitHub         3. Matplotlib         4. SQL
Categoria    Testes Projeto    Testes Projeto        Testes Projeto Testes
Estudante
João            100      80        90      90            60      70     70
Maria           100     100        70      70            80      70     80

                                                                     \
Semana                   3                                4
Tópico            5. NumPy         6. POO         7. Pandas
Categoria Projeto   Testes Projeto Testes Projeto    Testes Projeto
Estudante
João           80       80      90     70      80        70     100
Maria          70       60      60     90      80        70      70


Semana
Tópico    8. Estatística
Categoria         Testes Projeto
Estudante
João                  80      90
Maria                 80      80

Pivot Table

In [16]:
df.pivot(
    index=['Estudante'],
    columns=['Categoria', 'Semana', 'Tópico'],
    values=['Nota']
)

               Nota                                                            \
Categoria    Testes   Projeto    Testes   Projeto        Testes       Projeto
Semana            1         1         1         1             2             2
Tópico    1. Python 1. Python 2. GitHub 2. GitHub 3. Matplotlib 3. Matplotlib
Estudante
João            100        80        90        90            60            70
Maria           100       100        70        70            80            70

                                                                               \
Categoria Testes Projeto   Testes  Projeto Testes Projeto    Testes   Projeto
Semana         2       2        3        3      3       3         4         4
Tópico    4. SQL  4. SQL 5. NumPy 5. NumPy 6. POO  6. POO 7. Pandas 7. Pandas
Estudante
João          70      80       80       90     70      80        70       100
Maria         80      70       60       60     90      80        70        70


Categoria         Testes        Projeto
Semana                 4              4
Tópico    8. Estatística 8. Estatística
Estudante
João                  80             90
Maria                 80             80

In [17]:
df.pivot(
    index=['Estudante'],
    columns=['Semana', 'Tópico'],
    values=['Nota']
)

ValueError: Index contains duplicate entries, cannot reshape

In [18]:

df.pivot_table(
    index = ['Estudante'],
    columns = ['Semana', 'Tópico'],
    values = ['Nota'],
    aggfunc='count'
)

               Nota                                                           \
Semana            1                       2               3                4
Tópico    1. Python 2. GitHub 3. Matplotlib 4. SQL 5. NumPy 6. POO 7. Pandas
Estudante
João              2         2             2      2        2      2         2
Maria             2         2             2      2        2      2         2


Semana
Tópico    8. Estatística
Estudante
João                   2
Maria                  2

In [19]:
df.pivot_table(
    index = ['Estudante'],
    columns = ['Semana', 'Tópico'],
    values = ['Nota'],
    aggfunc='sum'
)

               Nota                                                           \
Semana            1                       2               3                4
Tópico    1. Python 2. GitHub 3. Matplotlib 4. SQL 5. NumPy 6. POO 7. Pandas
Estudante
João            180       180           130    150      170    150       170
Maria           200       140           150    150      120    170       140


Semana
Tópico    8. Estatística
Estudante
João                 170
Maria                160

In [20]:
df.pivot_table(
    index = ['Estudante'],
    columns = ['Semana', 'Tópico'],
    values = ['Nota']
)

               Nota                                                           \
Semana            1                       2               3                4
Tópico    1. Python 2. GitHub 3. Matplotlib 4. SQL 5. NumPy 6. POO 7. Pandas
Estudante
João           90.0      90.0          65.0   75.0     85.0   75.0      85.0
Maria         100.0      70.0          75.0   75.0     60.0   85.0      70.0


Semana
Tópico    8. Estatística
Estudante
João                85.0
Maria               80.0

In [24]:
df.groupby(['Estudante', 'Semana', 'Tópico'])['Nota'].mean()

Estudante  Semana  Tópico
João       1       1. Python          90.0
                   2. GitHub          90.0
           2       3. Matplotlib      65.0
                   4. SQL             75.0
           3       5. NumPy           85.0
                   6. POO             75.0
           4       7. Pandas          85.0
                   8. Estatística     85.0
Maria      1       1. Python         100.0
                   2. GitHub          70.0
           2       3. Matplotlib      75.0
                   4. SQL             75.0
           3       5. NumPy           60.0
                   6. POO             85.0
           4       7. Pandas          70.0
                   8. Estatística     80.0
Name: Nota, dtype: float64

In [27]:
df.groupby(['Estudante', 'Semana', 'Tópico'])['Nota'].mean().unstack(level=[1,2])

Semana            1                       2               3                4  \
Tópico    1. Python 2. GitHub 3. Matplotlib 4. SQL 5. NumPy 6. POO 7. Pandas
Estudante
João           90.0      90.0          65.0   75.0     85.0   75.0      85.0
Maria         100.0      70.0          75.0   75.0     60.0   85.0      70.0

Semana
Tópico    8. Estatística
Estudante
João                85.0
Maria               80.0