In [1]:
import pandas as pd

dados = {
    'produto':['Cama King','Sofa', 'Pc', 'Iphone 16 Pro', 'Fogão'],
    'preco':[2000,2500,5000,6000,2000],
    'quantidade':[4,5,3,2,10]
}
df = pd.DataFrame(dados)
df

         produto  preco  quantidade
0      Cama King   2000           4
1           Sofa   2500           5
2             Pc   5000           3
3  Iphone 16 Pro   6000           2
4          Fogão   2000          10

In [7]:
df['valor_total'] = df.apply(lambda x: x['preco'] * x['quantidade'] , axis=1)

In [8]:
df

         produto  preco  quantidade  valor_total
0      Cama King   2000           4         8000
1           Sofa   2500           5        12500
2             Pc   5000           3        15000
3  Iphone 16 Pro   6000           2        12000
4          Fogão   2000          10        20000