In [2]:
import pandas as pd

dados = {
    'produtos':[
        'Iphone 17 Pro Max',
        'Iphone 17',
        'S25 FE',
        'Motorola Edge 60 Fusion',
        'Samsung Galaxy A57',
        'Xiaomi Poco X7 Pro',
        'Iphone 16',
        'Xiaomi 15T',
        'Edge 70 Pro'
    ],
    'preco':[10000, 5598, 3100, 3000, 2000, 2500, 5000, 3500, 4000]
}

df = pd.DataFrame(dados)
df

                  produtos  preco
0        Iphone 17 Pro Max  10000
1                Iphone 17   5598
2                   S25 FE   3100
3  Motorola Edge 60 Fusion   3000
4       Samsung Galaxy A57   2000
5       Xiaomi Poco X7 Pro   2500
6                Iphone 16   5000
7               Xiaomi 15T   3500
8              Edge 70 Pro   4000

In [4]:
def classificar_preco(preco):
    if preco <= 2000:
        return 'Barato'
    elif preco <= 3000:
        return 'Medio'
    else:
        return 'caro'

In [5]:
df['faixa_preco'] = df['preco'].apply(classificar_preco)

In [6]:
df

                  produtos  preco faixa_preco
0        Iphone 17 Pro Max  10000        caro
1                Iphone 17   5598        caro
2                   S25 FE   3100        caro
3  Motorola Edge 60 Fusion   3000       Medio
4       Samsung Galaxy A57   2000      Barato
5       Xiaomi Poco X7 Pro   2500       Medio
6                Iphone 16   5000        caro
7               Xiaomi 15T   3500        caro
8              Edge 70 Pro   4000        caro

In [7]:
df['preco_com_desconto'] = df['preco'].apply(lambda x: x - (x * 0.10))

In [8]:
df

                  produtos  preco faixa_preco  preco_com_desconto
0        Iphone 17 Pro Max  10000        caro              9000.0
1                Iphone 17   5598        caro              5038.2
2                   S25 FE   3100        caro              2790.0
3  Motorola Edge 60 Fusion   3000       Medio              2700.0
4       Samsung Galaxy A57   2000      Barato              1800.0
5       Xiaomi Poco X7 Pro   2500       Medio              2250.0
6                Iphone 16   5000        caro              4500.0
7               Xiaomi 15T   3500        caro              3150.0
8              Edge 70 Pro   4000        caro              3600.0