In [1]:
import pandas as pd
from pandas.core.dtypes import astype

dados = {
    'produto_id':[1,2,3,4,5,6],
    'categoria':[
        'Eletronicos e Tecnologia',
        'Moda e Vestuário',
        'Casa e Decoração',
        'Alimentos e Bebidas',
        'Beleza e Cuidados Pessoais',
        'Esportes e Lazer'
    ],
    'faturamento_01-2024':[5000, 3000, 3000, 2500, 1000, 900],
    'faturamento_02-2024':[6000, 2000, 1000, 500, 2000, 1000],
    'faturamento_03-2024':[3000, 2500, 1500, 800, 1000, 700]
}
df = pd.DataFrame(dados)

In [2]:
df

,produto_id,categoria,faturamento_01-2024,faturamento_02-2024,faturamento_03-2024
0,1,Eletronicos e Tecnologia,5000,6000,3000
1,2,Moda e Vestuário,3000,2000,2500
2,3,Casa e Decoração,3000,1000,1500
3,4,Alimentos e Bebidas,2500,500,800
4,5,Beleza e Cuidados Pessoais,1000,2000,1000
5,6,Esportes e Lazer,900,1000,700

In [3]:
df_melt = pd.melt(
    df,
    id_vars=['produto_id', 'categoria'],
        value_vars=[
        'faturamento_01-2024',
        'faturamento_02-2024',
        'faturamento_03-2024'
    ],
    var_name='mes',
    value_name='valor'
)

In [4]:
df_melt

    produto_id                   categoria                  mes  valor
0            1    Eletronicos e Tecnologia  faturamento_01-2024   5000
1            2            Moda e Vestuário  faturamento_01-2024   3000
2            3            Casa e Decoração  faturamento_01-2024   3000
3            4         Alimentos e Bebidas  faturamento_01-2024   2500
4            5  Beleza e Cuidados Pessoais  faturamento_01-2024   1000
5            6            Esportes e Lazer  faturamento_01-2024    900
6            1    Eletronicos e Tecnologia  faturamento_02-2024   6000
7            2            Moda e Vestuário  faturamento_02-2024   2000
8            3            Casa e Decoração  faturamento_02-2024   1000
9            4         Alimentos e Bebidas  faturamento_02-2024    500
10           5  Beleza e Cuidados Pessoais  faturamento_02-2024   2000
11           6            Esportes e Lazer  faturamento_02-2024   1000
12           1    Eletronicos e Tecnologia  faturamento_03-2024   3000
13           2            Moda e Vestuário  faturamento_03-2024   2500
14           3            Casa e Decoração  faturamento_03-2024   1500
15           4         Alimentos e Bebidas  faturamento_03-2024    800
16           5  Beleza e Cuidados Pessoais  faturamento_03-2024   1000
17           6            Esportes e Lazer  faturamento_03-2024    700

In [5]:
df_melt[['mes', 'ano']] = df_melt['mes'].str.rsplit('_', n=1, expand=True)

In [6]:
df_melt = df_melt.drop(columns=['mes'])

In [7]:
df_melt

    produto_id                   categoria  valor      ano
0            1    Eletronicos e Tecnologia   5000  01-2024
1            2            Moda e Vestuário   3000  01-2024
2            3            Casa e Decoração   3000  01-2024
3            4         Alimentos e Bebidas   2500  01-2024
4            5  Beleza e Cuidados Pessoais   1000  01-2024
5            6            Esportes e Lazer    900  01-2024
6            1    Eletronicos e Tecnologia   6000  02-2024
7            2            Moda e Vestuário   2000  02-2024
8            3            Casa e Decoração   1000  02-2024
9            4         Alimentos e Bebidas    500  02-2024
10           5  Beleza e Cuidados Pessoais   2000  02-2024
11           6            Esportes e Lazer   1000  02-2024
12           1    Eletronicos e Tecnologia   3000  03-2024
13           2            Moda e Vestuário   2500  03-2024
14           3            Casa e Decoração   1500  03-2024
15           4         Alimentos e Bebidas    800  03-2024
16           5  Beleza e Cuidados Pessoais   1000  03-2024
17           6            Esportes e Lazer    700  03-2024

In [8]:
df_melt[['mes', 'ano']] = df_melt['ano'].str.rsplit('-', expand=True)

In [9]:
df_melt

    produto_id                   categoria  valor   ano mes
0            1    Eletronicos e Tecnologia   5000  2024  01
1            2            Moda e Vestuário   3000  2024  01
2            3            Casa e Decoração   3000  2024  01
3            4         Alimentos e Bebidas   2500  2024  01
4            5  Beleza e Cuidados Pessoais   1000  2024  01
5            6            Esportes e Lazer    900  2024  01
6            1    Eletronicos e Tecnologia   6000  2024  02
7            2            Moda e Vestuário   2000  2024  02
8            3            Casa e Decoração   1000  2024  02
9            4         Alimentos e Bebidas    500  2024  02
10           5  Beleza e Cuidados Pessoais   2000  2024  02
11           6            Esportes e Lazer   1000  2024  02
12           1    Eletronicos e Tecnologia   3000  2024  03
13           2            Moda e Vestuário   2500  2024  03
14           3            Casa e Decoração   1500  2024  03
15           4         Alimentos e Bebidas    800  2024  03
16           5  Beleza e Cuidados Pessoais   1000  2024  03
17           6            Esportes e Lazer    700  2024  03

In [8]:
df_melt.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   produto_id  18 non-null     int64
 1   categoria   18 non-null     str
 2   mes         18 non-null     str
 3   valor       18 non-null     int64
dtypes: int64(2), str(2)
memory usage: 708.0 bytes

In [10]:
df_melt['mes'] = pd.to_datetime(df_melt['mes'], format='%m')

In [11]:
df_melt

    produto_id                   categoria  valor   ano        mes
0            1    Eletronicos e Tecnologia   5000  2024 1900-01-01
1            2            Moda e Vestuário   3000  2024 1900-01-01
2            3            Casa e Decoração   3000  2024 1900-01-01
3            4         Alimentos e Bebidas   2500  2024 1900-01-01
4            5  Beleza e Cuidados Pessoais   1000  2024 1900-01-01
5            6            Esportes e Lazer    900  2024 1900-01-01
6            1    Eletronicos e Tecnologia   6000  2024 1900-02-01
7            2            Moda e Vestuário   2000  2024 1900-02-01
8            3            Casa e Decoração   1000  2024 1900-02-01
9            4         Alimentos e Bebidas    500  2024 1900-02-01
10           5  Beleza e Cuidados Pessoais   2000  2024 1900-02-01
11           6            Esportes e Lazer   1000  2024 1900-02-01
12           1    Eletronicos e Tecnologia   3000  2024 1900-03-01
13           2            Moda e Vestuário   2500  2024 1900-03-01
14           3            Casa e Decoração   1500  2024 1900-03-01
15           4         Alimentos e Bebidas    800  2024 1900-03-01
16           5  Beleza e Cuidados Pessoais   1000  2024 1900-03-01
17           6            Esportes e Lazer    700  2024 1900-03-01

In [12]:
df_melt['mes'] = df_melt['mes'].dt.month
df_melt

    produto_id                   categoria  valor   ano  mes
0            1    Eletronicos e Tecnologia   5000  2024    1
1            2            Moda e Vestuário   3000  2024    1
2            3            Casa e Decoração   3000  2024    1
3            4         Alimentos e Bebidas   2500  2024    1
4            5  Beleza e Cuidados Pessoais   1000  2024    1
5            6            Esportes e Lazer    900  2024    1
6            1    Eletronicos e Tecnologia   6000  2024    2
7            2            Moda e Vestuário   2000  2024    2
8            3            Casa e Decoração   1000  2024    2
9            4         Alimentos e Bebidas    500  2024    2
10           5  Beleza e Cuidados Pessoais   2000  2024    2
11           6            Esportes e Lazer   1000  2024    2
12           1    Eletronicos e Tecnologia   3000  2024    3
13           2            Moda e Vestuário   2500  2024    3
14           3            Casa e Decoração   1500  2024    3
15           4         Alimentos e Bebidas    800  2024    3
16           5  Beleza e Cuidados Pessoais   1000  2024    3
17           6            Esportes e Lazer    700  2024    3

In [14]:
df_melt['ano'] = pd.to_datetime(df_melt['ano'], format='%Y')
df_melt['ano'] = df_melt['ano'].dt.year

In [15]:
df_melt

    produto_id                   categoria  valor   ano  mes
0            1    Eletronicos e Tecnologia   5000  2024    1
1            2            Moda e Vestuário   3000  2024    1
2            3            Casa e Decoração   3000  2024    1
3            4         Alimentos e Bebidas   2500  2024    1
4            5  Beleza e Cuidados Pessoais   1000  2024    1
5            6            Esportes e Lazer    900  2024    1
6            1    Eletronicos e Tecnologia   6000  2024    2
7            2            Moda e Vestuário   2000  2024    2
8            3            Casa e Decoração   1000  2024    2
9            4         Alimentos e Bebidas    500  2024    2
10           5  Beleza e Cuidados Pessoais   2000  2024    2
11           6            Esportes e Lazer   1000  2024    2
12           1    Eletronicos e Tecnologia   3000  2024    3
13           2            Moda e Vestuário   2500  2024    3
14           3            Casa e Decoração   1500  2024    3
15           4         Alimentos e Bebidas    800  2024    3
16           5  Beleza e Cuidados Pessoais   1000  2024    3
17           6            Esportes e Lazer    700  2024    3

In [16]:
df_melt.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   produto_id  18 non-null     int64
 1   categoria   18 non-null     str
 2   valor       18 non-null     int64
 3   ano         18 non-null     int32
 4   mes         18 non-null     int32
dtypes: int32(2), int64(2), str(1)
memory usage: 708.0 bytes

In [17]:
df_melt['categoria'] = df_melt['categoria'].astype('category')

In [18]:
df_melt.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   produto_id  18 non-null     int64
 1   categoria   18 non-null     category
 2   valor       18 non-null     int64
 3   ano         18 non-null     int32
 4   mes         18 non-null     int32
dtypes: category(1), int32(2), int64(2)
memory usage: 630.0 bytes

In [19]:
df_melt.groupby(['categoria', 'mes'])['valor'].sum()

categoria                   mes
Alimentos e Bebidas         1      2500
                            2       500
                            3       800
Beleza e Cuidados Pessoais  1      1000
                            2      2000
                            3      1000
Casa e Decoração            1      3000
                            2      1000
                            3      1500
Eletronicos e Tecnologia    1      5000
                            2      6000
                            3      3000
Esportes e Lazer            1       900
                            2      1000
                            3       700
Moda e Vestuário            1      3000
                            2      2000
                            3      2500
Name: valor, dtype: int64

In [20]:
faturamento_esperado = 1000
filtro = df_melt[df_melt['valor'] < faturamento_esperado]

In [21]:
filtro

    produto_id            categoria  valor   ano  mes
5            6     Esportes e Lazer    900  2024    1
9            4  Alimentos e Bebidas    500  2024    2
15           4  Alimentos e Bebidas    800  2024    3
17           6     Esportes e Lazer    700  2024    3